'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BarChart3, Check, ChevronRight, LayoutDashboard, Package, RefreshCw, Save, Search, ShieldCheck, Truck, UserRound, Warehouse, Star } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { readSession } from '@/lib/session';

const apiBase = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:18080/api';
const money = value => `${new Intl.NumberFormat('ko-KR').format(value)}원`;
const orderStatuses = ['pending', 'confirmed', 'preparing', 'shipped', 'delivered', 'cancelled'];
const productStatuses = ['published', 'hidden', 'archived'];
const tabs = [
  ['dashboard', '대시보드', LayoutDashboard], ['members', '회원', UserRound], ['products', '상품', Package],
  ['inventory', '재고·물류', Warehouse], ['orders', '주문·배송', Truck], ['reviews', '리뷰', Star]
];

export default function AdminPage() {
  const [session, setSession] = useState(undefined);
  const [tab, setTab] = useState('dashboard');
  const [data, setData] = useState({ products: [], inventory: [], orders: [], users: [] });
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState('');
  const [query, setQuery] = useState('');
  const token = session?.accessToken;
  const headers = token ? { authorization: `Bearer ${token}` } : {};
  async function load() {
    setLoading(true);
    const options = { headers };
    const [products, inventory, orders, users] = await Promise.all([
      fetch(`${apiBase}/products?status=all`, options).then(r => r.json()),
      fetch(`${apiBase}/inventory`, options).then(r => r.json()),
      fetch(`${apiBase}/orders`, options).then(r => r.json()),
      fetch(`${apiBase}/auth/users`, options).then(r => r.json())
    ]);
    if (!products.items || !inventory.items || !orders.items || !users.items) throw new Error('관리자 데이터를 불러오지 못했습니다.');
    setData({ products: products.items, inventory: inventory.items, orders: orders.items, users: users.items });
    setLoading(false);
  }
  useEffect(() => setSession(readSession()), []);
  useEffect(() => { if (session?.user?.role === 'admin') load().catch(error => { setLoading(false); setMessage(error.message); }); else if (session) setLoading(false); }, [session]);
  const stockMap = useMemo(() => Object.fromEntries(data.inventory.map(item => [item.product_id, item.available_qty])), [data.inventory]);
  const stats = useMemo(() => ({ revenue: data.orders.reduce((sum, order) => sum + (order.total_amount || 0), 0), pending: data.orders.filter(order => ['pending', 'confirmed'].includes(order.status)).length, shipped: data.orders.filter(order => ['preparing', 'shipped'].includes(order.status)).length, lowStock: data.products.filter(product => (stockMap[product.id] ?? product.stock ?? 0) < 5).length }), [data, stockMap]);
  const filteredUsers = data.users.filter(user => `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase()));
  async function updateProduct(id, changes) { const response = await fetch(`${apiBase}/products/${id}`, { method: 'PATCH', headers: { 'content-type': 'application/json', ...headers }, body: JSON.stringify(changes) }); if (!response.ok) throw new Error('상품 저장 실패'); setMessage('상품 정보를 저장했습니다.'); await load(); }
  async function updateStock(id, value) { const response = await fetch(`${apiBase}/inventory/${id}`, { method: 'PATCH', headers: { 'content-type': 'application/json', ...headers }, body: JSON.stringify({ availableQty: Number(value) }) }); if (!response.ok) throw new Error('재고 저장 실패'); setMessage('재고를 저장했습니다.'); await load(); }
  async function updateOrder(id, status) { const response = await fetch(`${apiBase}/orders/${id}/status`, { method: 'PATCH', headers: { 'content-type': 'application/json', ...headers }, body: JSON.stringify({ status }) }); if (!response.ok) throw new Error('주문 상태 저장 실패'); setMessage('주문 상태를 저장했습니다.'); await load(); }
  if (session !== undefined && session?.user?.role !== 'admin') return <AccessDenied />;
  return <main className="min-h-screen bg-[#f4f6fa] text-slate-950"><div className="flex min-h-screen"><aside className="hidden w-64 shrink-0 border-r border-slate-200 bg-white p-5 lg:block"><a href="/" className="block px-3 py-4 text-xl font-black tracking-[-.11em]">TECH<span className="text-blue-600">ZONE</span><span className="ml-2 text-[9px] tracking-[.2em] text-slate-400">CMS</span></a><nav className="mt-8 grid gap-1">{tabs.map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold ${tab === id ? 'bg-slate-950 text-white' : 'text-slate-500 hover:bg-slate-100'}`}><Icon size={17}/>{label}<ChevronRight className="ml-auto" size={14}/></button>)}</nav><div className="mt-auto pt-20"><a href="/" className="flex items-center gap-2 px-3 text-xs font-bold text-slate-400"><ArrowLeft size={14}/> 스토어로 돌아가기</a></div></aside><section className="min-w-0 flex-1 px-5 py-6 md:px-8"><header className="flex items-center justify-between border-b border-slate-200 pb-5"><div><p className="text-[10px] font-bold tracking-[.24em] text-blue-600">TECHZONE OPERATIONS</p><h1 className="mt-2 text-2xl font-black">{tabs.find(item => item[0] === tab)?.[1]}</h1></div><div className="flex items-center gap-2"><Button variant="outline" size="sm" onClick={() => load()}><RefreshCw className="mr-2" size={14}/> 새로고침</Button><span className="hidden rounded-full bg-white px-3 py-2 text-xs font-bold md:inline">{session?.user?.name}</span></div></header><div className="flex gap-2 overflow-x-auto py-4 lg:hidden">{tabs.map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${tab === id ? 'bg-slate-950 text-white' : 'bg-white text-slate-500'}`}>{label}</button>)}</div>{message && <p role="status" className="mt-4 rounded-xl bg-blue-50 p-4 text-sm text-blue-700">{message}</p>}{loading ? <p className="mt-8 rounded-2xl bg-white p-8 text-sm">운영 데이터를 불러오는 중…</p> : <div className="mt-8">{tab === 'dashboard' && <Dashboard data={data} stats={stats}/>} {tab === 'members' && <Members users={filteredUsers} query={query} setQuery={setQuery}/>} {tab === 'products' && <Products products={data.products} onSave={updateProduct}/>} {tab === 'inventory' && <Inventory products={data.products} stockMap={stockMap} onSave={updateStock}/>} {tab === 'orders' && <Orders orders={data.orders} onSave={updateOrder}/>} {tab === 'reviews' && <Reviews/>}</div>}</section></div></main>;
}

function AccessDenied() { return <main className="grid min-h-screen place-items-center bg-[#f4f6fa] px-5"><div className="rounded-3xl bg-white p-10 text-center shadow-sm"><ShieldCheck className="mx-auto text-blue-600"/><h1 className="mt-5 text-3xl font-black">관리자 계정이 필요합니다</h1><p className="mt-3 text-sm text-slate-500">운영 콘솔은 관리자 권한으로 로그인한 계정만 사용할 수 있습니다.</p><a href="/login/" className="mt-8 inline-flex rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">관리자 로그인</a></div></main>; }
function Dashboard({ data, stats }) { const counts = ['pending', 'confirmed', 'preparing', 'shipped', 'delivered'].map(status => ({ status, value: data.orders.filter(order => order.status === status).length })); const max = Math.max(...counts.map(item => item.value), 1); return <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['총 매출', money(stats.revenue), '지난 주문 기준'], ['처리 대기', stats.pending, '주문·확인 필요'], ['배송 진행', stats.shipped, '출고·배송 중'], ['재고 주의', stats.lowStock, '5개 미만 상품']].map(([label, value, note]) => <article key={label} className="rounded-2xl bg-white p-5"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-3 text-3xl font-black tracking-tight">{value}</p><p className="mt-2 text-xs text-slate-400">{note}</p></article>)}</div><div className="grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><section className="rounded-2xl bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold tracking-[.2em] text-blue-600">ORDER FUNNEL</p><h2 className="mt-2 text-xl font-black">주문 상태 현황</h2></div><BarChart3 className="text-blue-600"/></div><div className="mt-8 flex h-56 items-end gap-4 border-b border-slate-100 pb-0">{counts.map(item => <div key={item.status} className="flex flex-1 flex-col items-center gap-2"><span className="text-xs font-bold">{item.value}</span><div className="w-full rounded-t-xl bg-blue-600 transition-all" style={{ height: `${Math.max(item.value / max * 170, 10)}px` }}/><span className="text-[10px] text-slate-400">{item.status}</span></div>)}</div></section><section className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-[10px] font-bold tracking-[.2em] text-blue-300">QUICK VIEW</p><h2 className="mt-2 text-xl font-black">운영 바로가기</h2><div className="mt-6 grid gap-3 text-sm"><p className="rounded-xl bg-white/10 p-4">회원 {data.users.length}명</p><p className="rounded-xl bg-white/10 p-4">상품 {data.products.length}개</p><p className="rounded-xl bg-white/10 p-4">주문 {data.orders.length}건</p></div></section></div></div>; }
function Members({ users, query, setQuery }) { return <section className="rounded-2xl bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.2em] text-blue-600">CUSTOMERS</p><h2 className="mt-2 text-xl font-black">회원 관리 <span className="text-sm text-slate-400">{users.length}</span></h2></div><label className="flex items-center gap-2 rounded-xl border px-3 py-2 text-sm"><Search size={15} className="text-slate-400"/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="이름 또는 이메일 검색" className="w-52 outline-none"/></label></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b text-xs text-slate-400"><tr><th className="pb-3">회원</th><th className="pb-3">이메일</th><th className="pb-3">권한</th><th className="pb-3">가입일</th><th className="pb-3">상태</th></tr></thead><tbody className="divide-y">{users.map(user => <tr key={user.id}><td className="py-4 font-bold">{user.name}</td><td className="py-4 text-slate-500">{user.email}</td><td className="py-4"><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">{user.role}</span></td><td className="py-4 text-slate-400">{new Date(user.createdAt).toLocaleDateString('ko-KR')}</td><td className="py-4 text-xs font-bold text-emerald-600">활성</td></tr>)}</tbody></table></div></section>; }
function Products({ products, onSave }) { return <section className="rounded-2xl bg-white p-6"><SectionTitle label="CATALOG" title="상품 관리" count={products.length}/><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b text-xs text-slate-400"><tr><th className="pb-3">상품</th><th className="pb-3">카테고리</th><th className="pb-3">가격</th><th className="pb-3">상태</th><th className="pb-3">저장</th></tr></thead><tbody className="divide-y">{products.map(product => <ProductRow key={product.id} product={product} onSave={onSave}/>)}</tbody></table></div></section>; }
function Inventory({ products, stockMap, onSave }) { return <section className="rounded-2xl bg-slate-950 p-6 text-white"><SectionTitle label="FULFILLMENT" title="재고·물류 관리" count={products.length}/><div className="mt-6 grid gap-3 md:grid-cols-2">{products.map(product => <StockRow key={product.id} product={product} value={stockMap[product.id] ?? product.stock ?? 0} onSave={onSave}/>)}</div></section>; }
function Orders({ orders, onSave }) { return <section className="rounded-2xl bg-white p-6"><SectionTitle label="ORDER & SHIPPING" title="주문·배송 관리" count={orders.length}/><div className="mt-6 grid gap-3">{orders.length ? orders.map(order => <OrderRow key={order.id} order={order} onSave={onSave}/>) : <Empty text="아직 주문이 없습니다."/>}</div></section>; }
function Reviews() { return <section className="rounded-2xl bg-white p-6"><SectionTitle label="CUSTOMER VOICE" title="리뷰 관리" count={0}/><div className="mt-6 rounded-2xl border border-dashed border-slate-200 p-12 text-center"><Star className="mx-auto text-amber-400"/><h3 className="mt-4 text-lg font-black">리뷰 데이터가 아직 없습니다</h3><p className="mt-2 text-sm text-slate-500">상품 리뷰 서비스 연결 후 평점, 신고, 공개 상태를 이 화면에서 관리할 수 있습니다.</p></div></section>; }
function SectionTitle({ label, title, count }) { return <div><p className="text-[10px] font-bold tracking-[.2em] text-blue-600">{label}</p><h2 className="mt-2 text-xl font-black">{title} <span className="text-sm text-slate-400">{count}</span></h2></div>; }
function Empty({ text }) { return <p className="rounded-xl bg-slate-50 p-8 text-center text-sm text-slate-500">{text}</p>; }
function ProductRow({ product, onSave }) { const [price, setPrice] = useState(product.price); const [status, setStatus] = useState(product.status || 'published'); return <tr><td className="py-4"><div className="flex items-center gap-3"><img src={product.image} alt="" className="h-12 w-12 rounded-lg object-cover"/><div><p className="font-bold">{product.name}</p><p className="text-xs text-slate-400">{product.brand}</p></div></div></td><td className="py-4 text-slate-500">{product.category}</td><td className="py-4"><input aria-label={`${product.name} 가격`} type="number" value={price} onChange={event => setPrice(event.target.value)} className="w-32 rounded-lg border p-2"/></td><td className="py-4"><select aria-label={`${product.name} 상태`} value={status} onChange={event => setStatus(event.target.value)} className="rounded-lg border p-2">{productStatuses.map(value => <option key={value} value={value}>{value}</option>)}</select></td><td className="py-4"><Button size="sm" onClick={() => onSave(product.id, { price: Number(price), status })}><Save size={14}/></Button></td></tr>; }
function StockRow({ product, value, onSave }) { const [stock, setStock] = useState(value); return <div className="flex items-center justify-between gap-3 rounded-xl border border-slate-800 p-4"><div><p className="truncate text-sm font-bold">{product.name}</p><p className="mt-1 text-xs text-slate-400">SKU {product.id.slice(0, 8)}</p></div><div className="flex items-center gap-2"><input aria-label={`${product.name} 재고`} type="number" min="0" value={stock} onChange={event => setStock(event.target.value)} className="w-20 rounded-lg border border-slate-700 bg-slate-900 p-2 text-right text-sm"/><Button size="sm" variant="secondary" onClick={() => onSave(product.id, stock)}><Check size={14}/></Button></div></div>; }
function OrderRow({ order, onSave }) { return <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><div><p className="font-bold">{order.order_number}</p><p className="mt-1 text-xs text-slate-500">상품 {order.item_count}개 · {money(order.total_amount)} · {order.recipient}</p></div><div className="flex items-center gap-3"><span className="hidden text-xs text-slate-400 md:inline">배송 상태</span><select aria-label={`${order.order_number} 상태`} value={order.status} onChange={event => onSave(order.id, event.target.value)} className="rounded-lg border bg-white p-2 text-xs">{orderStatuses.map(value => <option key={value} value={value}>{value}</option>)}</select></div></div>; }
