'use client';
import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Check, Package, RefreshCw, Save, Search, ShieldCheck, Star, Truck, UserRound, Warehouse } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { readSession } from '@/lib/session';
const apiBase = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:18080/api';
const money = value => `${new Intl.NumberFormat('ko-KR').format(value)}원`;
const tabs = [['dashboard','대시보드'],['members','회원'],['products','상품'],['inventory','재고·물류'],['orders','주문·배송'],['reviews','리뷰']];
const statuses = ['pending','confirmed','preparing','shipped','delivered','cancelled'];
export default function AdminPage() { const [session,setSession]=useState(undefined); const [tab,setTab]=useState('dashboard'); const [data,setData]=useState({products:[],inventory:[],orders:[],users:[],reviews:[]}); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(''); const [query,setQuery]=useState(''); const token=session?.accessToken; const auth={authorization:`Bearer ${token}`};
 async function load(){setLoading(true);const o={headers:auth};const [products,inventory,orders,users,reviews]=await Promise.all([fetch(`${apiBase}/products?status=all`,o).then(r=>r.json()),fetch(`${apiBase}/inventory`,o).then(r=>r.json()),fetch(`${apiBase}/orders`,o).then(r=>r.json()),fetch(`${apiBase}/auth/users`,o).then(r=>r.json()),fetch(`${apiBase}/reviews`,o).then(r=>r.json())]);if(!products.items||!inventory.items||!orders.items||!users.items||!reviews.items)throw Error('관리자 데이터를 불러오지 못했습니다.');setData({products:products.items,inventory:inventory.items,orders:orders.items,users:users.items,reviews:reviews.items});setLoading(false);}
 useEffect(()=>setSession(readSession()),[]); useEffect(()=>{if(session?.user?.role==='admin')load().catch(e=>{setLoading(false);setMessage(e.message)});else if(session)setLoading(false)},[session]);
 const stock=useMemo(()=>Object.fromEntries(data.inventory.map(x=>[x.product_id,x.available_qty])),[data.inventory]); const stats={revenue:data.orders.reduce((a,x)=>a+(x.total_amount||0),0),pending:data.orders.filter(x=>['pending','confirmed'].includes(x.status)).length,shipping:data.orders.filter(x=>['preparing','shipped'].includes(x.status)).length,low:data.products.filter(x=>(stock[x.id]??x.stock??0)<5).length}; const users=data.users.filter(x=>`${x.name} ${x.email}`.toLowerCase().includes(query.toLowerCase()));
 async function save(path,body,success){const r=await fetch(`${apiBase}${path}`,{method:'PATCH',headers:{'content-type':'application/json',...auth},body:JSON.stringify(body)});if(!r.ok)throw Error('저장에 실패했습니다.');setMessage(success);await load();}
 if(session!==undefined&&session?.user?.role!=='admin')return <main className="grid min-h-screen place-items-center bg-slate-100"><div className="rounded-3xl bg-white p-10 text-center"><ShieldCheck className="mx-auto text-blue-600"/><h1 className="mt-4 text-2xl font-black">관리자 계정이 필요합니다</h1><a href="/login/" className="mt-6 inline-block rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">관리자 로그인</a></div></main>;
 return <main className="min-h-screen bg-[#f4f6fa] text-slate-950"><div className="flex min-h-screen"><aside className="hidden w-60 shrink-0 bg-white p-5 lg:block"><a href="/" className="text-xl font-black">TECH<span className="text-blue-600">ZONE</span><small className="ml-2 text-[9px] text-slate-400">CMS</small></a><nav className="mt-10 grid gap-2">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-xl px-3 py-3 text-left text-sm font-bold ${tab===id?'bg-slate-950 text-white':'text-slate-500 hover:bg-slate-100'}`}>{label}</button>)}</nav></aside><section className="min-w-0 flex-1 p-5 md:p-8"><header className="flex items-center justify-between border-b pb-5"><div><p className="text-[10px] font-bold tracking-[.2em] text-blue-600">TECHZONE OPERATIONS</p><h1 className="mt-2 text-3xl font-black">{tabs.find(x=>x[0]===tab)?.[1]}</h1></div><Button variant="outline" size="sm" onClick={()=>load()}><RefreshCw className="mr-2" size={14}/> 새로고침</Button></header><div className="flex gap-2 overflow-x-auto py-4 lg:hidden">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${tab===id?'bg-slate-950 text-white':'bg-white'}`}>{label}</button>)}</div>{message&&<p role="status" className="my-4 rounded-xl bg-blue-50 p-4 text-sm text-blue-700">{message}</p>}{loading?<p className="mt-8 rounded-2xl bg-white p-8">운영 데이터를 불러오는 중…</p>:<div className="mt-6">{tab==='dashboard'&&<Dashboard data={data} stats={stats}/>} {tab==='members'&&<Members users={users} query={query} setQuery={setQuery}/>} {tab==='products'&&<Products products={data.products} save={save}/>} {tab==='inventory'&&<Inventory products={data.products} stock={stock} save={save}/>} {tab==='orders'&&<Orders orders={data.orders} save={save}/>} {tab==='reviews'&&<Reviews reviews={data.reviews} save={save}/>}</div>}</section></div></main> }
function Dashboard({data,stats}){const bars=statuses.slice(0,5).map(s=>[s,data.orders.filter(x=>x.status===s).length]);const max=Math.max(...bars.map(x=>x[1]),1);return <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['총 매출',money(stats.revenue)],['처리 대기',stats.pending],['배송 진행',stats.shipping],['재고 주의',stats.low]].map(x=><article key={x[0]} className="rounded-2xl bg-white p-5"><p className="text-xs text-slate-400">{x[0]}</p><p className="mt-3 text-3xl font-black">{x[1]}</p></article>)}</div><section className="rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-black">주문 상태 차트</h2><BarChart3 className="text-blue-600"/></div><div className="mt-8 flex h-56 items-end gap-4">{bars.map(x=><div key={x[0]} className="flex flex-1 flex-col items-center gap-2"><b>{x[1]}</b><div className="w-full rounded-t-xl bg-blue-600" style={{height:`${Math.max(x[1]/max*170,10)}px`}}/><small className="text-[10px] text-slate-400">{x[0]}</small></div>)}</div></section><div className="grid gap-4 md:grid-cols-3">{[['회원',data.users.length,UserRound],['상품',data.products.length,Package],['주문',data.orders.length,Truck]].map(([label,count,Icon])=><div key={label} className="rounded-2xl bg-slate-950 p-5 text-white"><Icon className="text-blue-300"/><p className="mt-5 text-sm text-slate-400">{label}</p><b className="text-3xl">{count}</b></div>)}</div></div>}
function Members({users,query,setQuery}){return <Panel title="회원 관리" label="CUSTOMERS" count={users.length}><label className="mb-5 flex items-center gap-2 rounded-xl border px-3 py-2 text-sm"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="이름·이메일 검색" className="w-full outline-none"/></label><Table headers={['회원','이메일','권한','가입일','상태']}>{users.map(u=><tr key={u.id}><td className="py-4 font-bold">{u.name}</td><td>{u.email}</td><td><span className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-700">{u.role}</span></td><td className="text-slate-400">{new Date(u.createdAt).toLocaleDateString('ko-KR')}</td><td className="text-emerald-600">활성</td></tr>)}</Table></Panel>}
function Products({products,save}){return <Panel title="상품 관리" label="CATALOG" count={products.length}><Table headers={['상품','카테고리','가격','상태','저장']}>{products.map(p=><ProductRow key={p.id} p={p} save={save}/>)}</Table></Panel>}
function ProductRow({p,save}){const [price,setPrice]=useState(p.price);const [status,setStatus]=useState(p.status||'published');return <tr><td className="py-4 font-bold">{p.name}<small className="ml-2 text-slate-400">{p.brand}</small></td><td>{p.category}</td><td><input type="number" value={price} onChange={e=>setPrice(e.target.value)} className="w-28 rounded border p-2"/></td><td><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded border p-2"><option>published</option><option>hidden</option><option>archived</option></select></td><td><Button size="sm" onClick={()=>save(`/products/${p.id}`,{price:Number(price),status},'상품을 저장했습니다.')}><Save size={14}/></Button></td></tr>}
function Inventory({products,stock,save}){return <Panel title="재고·물류 관리" label="FULFILLMENT" count={products.length} dark><div className="grid gap-3 md:grid-cols-2">{products.map(p=><StockRow key={p.id} p={p} value={stock[p.id]??p.stock??0} save={save}/>)}</div></Panel>}
function StockRow({p,value,save}){const [qty,setQty]=useState(value);return <div className="flex items-center justify-between rounded-xl border border-slate-800 p-4"><span className="text-sm font-bold">{p.name}</span><div className="flex gap-2"><input type="number" value={qty} onChange={e=>setQty(e.target.value)} className="w-20 rounded border border-slate-700 bg-slate-900 p-2 text-right"/><Button size="sm" variant="secondary" onClick={()=>save(`/inventory/${p.id}`,{availableQty:Number(qty)},'재고를 저장했습니다.')}><Check size={14}/></Button></div></div>}
function Orders({orders,save}){return <Panel title="주문·배송 관리" label="ORDER & SHIPPING" count={orders.length}><div className="grid gap-3">{orders.map(o=><div key={o.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><div><b>{o.order_number}</b><p className="mt-1 text-xs text-slate-500">{o.recipient} · 상품 {o.item_count}개 · {money(o.total_amount)}</p></div><select value={o.status} onChange={e=>save(`/orders/${o.id}/status`,{status:e.target.value},'주문 상태를 저장했습니다.')} className="rounded border bg-white p-2 text-xs">{statuses.map(s=><option key={s}>{s}</option>)}</select></div>)}</div></Panel>}
function Reviews({reviews,save}){return <Panel title="리뷰 관리" label="CUSTOMER VOICE" count={reviews.length}>{reviews.length?<div className="grid gap-3">{reviews.map(r=><div key={r.id} className="flex flex-wrap justify-between gap-4 rounded-xl bg-slate-50 p-4"><div><b className="text-amber-500">{'★'.repeat(r.rating)}</b><span className="ml-2 text-xs text-slate-400">{r.user_name}</span><p className="mt-2 text-sm">{r.body}</p></div><select value={r.status} onChange={e=>save(`/reviews/${r.id}`,{status:e.target.value},'리뷰 상태를 저장했습니다.')} className="rounded border bg-white p-2 text-xs"><option>pending</option><option>published</option><option>hidden</option><option>rejected</option></select></div>)}</div>:<div className="rounded-xl border border-dashed p-12 text-center"><Star className="mx-auto text-amber-400"/><p className="mt-3 text-sm text-slate-500">아직 등록된 리뷰가 없습니다.</p></div>}</Panel>}
function Panel({title,label,count,children,dark=false}){return <section className={`rounded-2xl p-6 ${dark?'bg-slate-950 text-white':'bg-white'}`}><p className="text-[10px] font-bold tracking-[.2em] text-blue-600">{label}</p><h2 className="mt-2 text-xl font-black">{title} <span className="text-sm text-slate-400">{count}</span></h2><div className="mt-6">{children}</div></section>}
function Table({headers,children}){return <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b text-xs text-slate-400"><tr>{headers.map(h=><th key={h} className="pb-3">{h}</th>)}</tr></thead><tbody className="divide-y">{children}</tbody></table></div>}
