'use client';
import { flexRender, getCoreRowModel, getFilteredRowModel, getPaginationRowModel, getSortedRowModel, useReactTable } from '@tanstack/react-table';
import { useState } from 'react';
import { ChevronLeft, ChevronRight, Search } from 'lucide-react';
export default function DataTable({ data, columns, placeholder = '검색어를 입력하세요' }) {
  const [sorting, setSorting] = useState([]); const [globalFilter, setGlobalFilter] = useState('');
  const table = useReactTable({ data, columns, state: { sorting, globalFilter }, onSortingChange: setSorting, onGlobalFilterChange: setGlobalFilter, getCoreRowModel: getCoreRowModel(), getFilteredRowModel: getFilteredRowModel(), getSortedRowModel: getSortedRowModel(), getPaginationRowModel: getPaginationRowModel(), globalFilterFn: 'includesString', initialState: { pagination: { pageSize: 10 } } });
  return <div><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><label className="flex min-w-64 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><Search size={15} className="text-slate-400"/><input value={globalFilter ?? ''} onChange={event => setGlobalFilter(event.target.value)} placeholder={placeholder} className="w-full outline-none"/></label><span className="text-xs text-slate-400">{table.getFilteredRowModel().rows.length}건</span></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b text-xs text-slate-400"><tr>{table.getHeaderGroups().map(group => group.headers.map(header => <th key={header.id} className="cursor-pointer pb-3" onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header, header.getContext())}{({asc:' ↑',desc:' ↓'} as Record<string, string>)[String(header.column.getIsSorted())] || ''}</th>))}</tr></thead><tbody className="divide-y">{table.getRowModel().rows.length ? table.getRowModel().rows.map(row => <tr key={row.id}>{row.getVisibleCells().map(cell => <td key={cell.id} className="py-4">{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>) : <tr><td colSpan={columns.length} className="py-12 text-center text-slate-400">검색 결과가 없습니다.</td></tr>}</tbody></table></div><div className="mt-5 flex items-center justify-between text-xs text-slate-500"><span>페이지 {table.getState().pagination.pageIndex + 1} / {table.getPageCount() || 1}</span><div className="flex gap-2"><button disabled={!table.getCanPreviousPage()} onClick={() => table.previousPage()} className="rounded-lg border p-2 disabled:opacity-30"><ChevronLeft size={15}/></button><button disabled={!table.getCanNextPage()} onClick={() => table.nextPage()} className="rounded-lg border p-2 disabled:opacity-30"><ChevronRight size={15}/></button></div></div></div>;
}
