'use client';
import { useEffect, useState } from 'react';
import { Heart, Package, UserRound } from 'lucide-react';
import StoreShell from '@/components/store/store-shell';
import ProductCard from '@/components/store/product-card';
import { api } from '@techzone/api-client/store';
import { readSession } from '@techzone/api-client/session';

export default function Page(){const[recent,setRecent]=useState([]),[wishlist,setWishlist]=useState([]);useEffect(()=>{setRecent(JSON.parse(localStorage.getItem('techzone-recent')||'[]'));const session=readSession();if(session)api(`/wishlists/${session.user.id}`).then(data=>setWishlist(data.items||[])).catch(()=>{});},[]);const session=typeof window==='undefined'?null:readSession();return <StoreShell><main className="mx-auto max-w-6xl px-4 py-14 md:px-8"><p className="text-xs font-black tracking-[.2em] text-indigo-600">MY TECHZONE</p><h1 className="mt-3 text-4xl font-black tracking-[-.06em]">마이페이지</h1><section className="mt-8 grid gap-4 md:grid-cols-3"><a href="/login/" className="rounded-2xl bg-indigo-600 p-6 text-white"><UserRound/><b className="mt-5 block text-xl">{session?`${session.user.name}님`:'로그인해 주세요'}</b><p className="mt-2 text-xs text-indigo-200">회원 정보와 혜택을 확인하세요.</p></a><a href="/orders/" className="rounded-2xl border p-6"><Package className="text-indigo-600"/><b className="mt-5 block text-xl">주문·배송</b><p className="mt-2 text-xs text-slate-400">주문 상태와 배송을 확인합니다.</p></a><a href="/guest-orders/" className="rounded-2xl border p-6"><Heart className="text-indigo-600"/><b className="mt-5 block text-xl">비회원 주문조회</b><p className="mt-2 text-xs text-slate-400">주문번호와 휴대폰으로 조회합니다.</p></a></section><Section title="찜한 상품" items={wishlist}/><Section title="최근 본 상품" items={recent}/></main></StoreShell>;}
function Section({title,items}){return <section className="mt-14"><h2 className="text-2xl font-black">{title}</h2>{items.length?<div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-4">{items.slice(0,4).map(item=><ProductCard key={item.id} product={item} compact/>)}</div>:<p className="mt-5 rounded-2xl bg-slate-50 p-8 text-sm text-slate-400">아직 상품이 없습니다.</p>}</section>;}
