'use client';

import { useEffect, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { authHeaders, readSession } from '@techzone/api-client/session';
const API = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:18080/api';
const won = value => `${new Intl.NumberFormat('ko-KR').format(Number(value || 0))}원`;

export default function AnalyticsPage() {
  const [data, setData] = useState(null);
  useEffect(() => { readSession(); const to = new Date(); const from = new Date(); from.setDate(to.getDate() - 89); fetch(`${API}/admin/dashboard?from=${from.toISOString().slice(0, 10)}&to=${to.toISOString().slice(0, 10)}`, { credentials: 'include', headers: authHeaders() }).then(response => response.json()).then(setData).catch(() => {}); }, []);
  return <main className="p-4 md:p-7 xl:p-9"><div className="mx-auto max-w-[1540px]"><p className="text-xs font-bold tracking-[.16em] text-indigo-600">OPERATIONS ANALYTICS</p><h1 className="mt-2 text-3xl font-black tracking-[-.05em] md:text-4xl">운영 분석</h1><p className="mt-2 text-sm text-slate-500">최근 90일의 매출 구성과 주문 흐름을 분석합니다.</p>{data ? <div className="mt-7 grid gap-6 xl:grid-cols-2"><Chart title="90일 매출 추이"><AreaChart data={data.trend}><defs><linearGradient id="analytics" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#4f46e5" stopOpacity={.35}/><stop offset="95%" stopColor="#4f46e5" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{ fontSize: 9 }}/><YAxis tickFormatter={value => `${Math.round(value / 10000)}만`}/><Tooltip formatter={value => won(value)}/><Area dataKey="revenue" name="매출" stroke="#4f46e5" fill="url(#analytics)" strokeWidth={2}/></AreaChart></Chart><Chart title="카테고리별 매출"><BarChart data={data.categorySales} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tickFormatter={value => `${Math.round(value / 10000)}만`}/><YAxis type="category" dataKey="name" width={70}/><Tooltip formatter={value => won(value)}/><Bar dataKey="value" name="매출" fill="#0ea5e9" radius={[0, 6, 6, 0]}/></BarChart></Chart><Chart title="브랜드별 매출"><BarChart data={data.brandSales}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis tickFormatter={value => `${Math.round(value / 10000)}만`}/><Tooltip formatter={value => won(value)}/><Bar dataKey="value" name="매출" fill="#14b8a6" radius={[6, 6, 0, 0]}/></BarChart></Chart><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black">핵심 수익 지표</h2><dl className="mt-5 grid grid-cols-2 gap-4">{[['총매출', won(data.kpis.grossSales.value)], ['순매출', won(data.kpis.netSales.value)], ['객단가', won(data.kpis.averageOrderValue.value)], ['환불률', `${data.kpis.refundRate.value}%`], ['결제 승인율', `${data.kpis.approvalRate.value}%`], ['주문', `${data.kpis.orders.value}건`]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-4"><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-2 text-xl font-black">{value}</dd></div>)}</dl></section></div> : <div className="mt-7 h-96 animate-pulse rounded-2xl bg-slate-200"/>}</div></main>;
}
function Chart({ title, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black">{title}</h2><div className="mt-6 h-80"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div></section>; }
