apiVersion: v1
kind: Secret
metadata:
  name: techzone-secrets
  namespace: techzone
type: Opaque
stringData:
  postgres-host: postgres.example.internal
  postgres-user: techzone
  postgres-password: CHANGE_ME
  database-url-gateway: postgres://CHANGE_ME/gateway
  database-url-auth: postgres://CHANGE_ME/auth
  database-url-catalog: postgres://CHANGE_ME/catalog
  database-url-cart: postgres://CHANGE_ME/cart
  database-url-order: postgres://CHANGE_ME/orders
  database-url-payment: postgres://CHANGE_ME/payments
  database-url-inventory: postgres://CHANGE_ME/inventory
  database-url-notification: postgres://CHANGE_ME/notifications
  database-url-search: postgres://CHANGE_ME/search
  database-url-media: postgres://CHANGE_ME/media
  database-url-fulfillment: postgres://CHANGE_ME/fulfillment
  database-url-procurement: postgres://CHANGE_ME/procurement
  database-url-admin: postgres://CHANGE_ME/admin
  rabbit-url: amqp://CHANGE_ME
  redis-url: redis://CHANGE_ME
  internal-api-key: CHANGE_ME
  auth-private-key-base64: REPLACE_WITH_BASE64_ENCODED_RS256_PRIVATE_KEY
