'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowRight, Heart, Menu, Search, ShoppingBag, UserRound, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { getCurrentUserId } from '@/lib/session';

const categories = ['전체', '스마트폰', '노트북', '오디오', '게이밍', '스마트홈', '웨어러블', '액세서리'];
const fallback = [
  { id: 'f1', name: 'NOVA Book Air 14', brand: 'NOVA', category: '노트북', price: 1499000, color: '스페이스 그레이', note: '하루 종일 이어지는 배터리와 선명한 2.8K 디스플레이.', image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1100&q=85' },
  { id: 'f2', name: 'Orbit Pro X', brand: 'ORBIT', category: '스마트폰', price: 1199000, color: '미드나이트', note: '손 안의 강력한 퍼포먼스. 50MP 트리플 카메라.', image: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=1100&q=85' },
  { id: 'f3', name: 'Sonic Max ANC', brand: 'SONIC', category: '오디오', price: 329000, color: '크림', note: '몰입을 방해하는 소음을 지우는 프리미엄 헤드폰.', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1100&q=85' },
  { id: 'f4', name: 'Arc Mechanical 75', brand: 'ARC', category: '게이밍', price: 219000, color: '오프화이트', note: '정교한 타건감과 자유로운 커스텀을 위한 키보드.', image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1100&q=85' },
];
const apiBase = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:18080/api';
const money = value => `${new Intl.NumberFormat('ko-KR').format(value)}원`;

export default function Home() {
  const [products, setProducts] = useState(fallback); const [selectedCategory, setSelectedCategory] = useState('전체'); const [cart, setCart] = useState([]); const [selected, setSelected] = useState(null); const [cartOpen, setCartOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [query, setQuery] = useState(''); const [online, setOnline] = useState(false); const [cartReady, setCartReady] = useState(false);
  useEffect(() => { fetch(`${apiBase}/products`).then(r => r.json()).then(data => { setProducts(data.items); setOnline(true); }).catch(() => {}); fetch(`${apiBase}/carts/${getCurrentUserId()}`).then(r => r.json()).then(data => { setCart((data.items || []).map(item => ({ id: item.product_id, name: item.name, brand: item.brand, image: item.image, price: item.price, quantity: item.quantity }))); setCartReady(true); }).catch(() => setCartReady(true)); }, []);
  const visible = useMemo(() => products.filter(product => (selectedCategory === '전체' || product.category === selectedCategory) && `${product.name} ${product.brand}`.toLowerCase().includes(query.toLowerCase())), [products, selectedCategory, query]);
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const syncItem = item => fetch(`${apiBase}/carts/${getCurrentUserId()}/items`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ productId: item.id, name: item.name, brand: item.brand, image: item.image, price: item.price, quantity: item.quantity }) }).catch(() => {});
  const add = product => { if (!cartReady) return; setCart(current => { const existing = current.find(item => item.id === product.id); const item = existing ? { ...existing, quantity: existing.quantity + 1 } : { ...product, quantity: 1 }; syncItem(item); return existing ? current.map(value => value.id === product.id ? item : value) : [...current, item]; }); setSelected(null); setCartOpen(true); };
  const change = (id, amount) => { if (!cartReady) return; setCart(current => { const existing = current.find(item => item.id === id); if (!existing) return current; const quantity = existing.quantity + amount; if (quantity < 1) { fetch(`${apiBase}/carts/${getCurrentUserId()}/items/${id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ quantity: 0 }) }).catch(() => {}); return current.filter(item => item.id !== id); } const item = { ...existing, quantity }; syncItem(item); return current.map(value => value.id === id ? item : value); }); };
  const placeOrder = async shipping => { const userId = getCurrentUserId(); const items = cart.map(item => ({ productId: item.id, name: item.name, brand: item.brand, image: item.image, price: item.price, quantity: item.quantity })); const response = await fetch(`${apiBase}/orders`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ userId, items, shipping }) }); if (!response.ok) throw new Error('주문 생성에 실패했습니다.'); const order = await response.json(); const payment = await fetch(`${apiBase}/payments/confirm`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ orderId: order.id, amount: order.totalAmount, paymentKey: `demo_${order.id}`, order: { userId, items } }) }); if (!payment.ok) throw new Error('결제 승인에 실패했습니다.'); await fetch(`${apiBase}/carts/${userId}`, { method: 'DELETE' }); setCart([]); return order; };
  return <main className="min-h-screen bg-[#f6f8fc] text-slate-950"><div className="bg-slate-950 py-2 text-center text-[11px] font-medium tracking-[.18em] text-blue-100">{online ? 'TECHZONE · LIVE CATALOG CONNECTED' : 'TECHZONE · NEW DIGITAL EXPERIENCE'}</div>
    <header className="sticky top-0 z-30 border-b border-slate-200 bg-[#f6f8fc]/90 px-5 backdrop-blur md:px-10"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between"><a href="#top" className="text-xl font-black tracking-[-.11em]">TECH<span className="text-blue-600">ZONE</span></a><nav className="hidden gap-7 text-sm font-semibold md:flex"><a href="#shop">스토어</a><a href="#story">테크 매거진</a><a href="#brands">브랜드</a><a href="/orders/">주문 내역</a></nav><div className="flex items-center gap-1"><Button variant="ghost" size="icon" aria-label="검색" onClick={() => setSearchOpen(!searchOpen)}><Search size={19}/></Button><a href="/login/" aria-label="계정" className="grid h-9 w-9 place-items-center rounded-md hover:bg-slate-100"><UserRound size={19}/></a><Button variant="ghost" size="icon" className="md:hidden" aria-label="메뉴"><Menu size={19}/></Button><Button variant="default" size="sm" onClick={() => setCartOpen(true)}><ShoppingBag size={15}/><span className="ml-2 hidden sm:inline">장바구니</span><span className="ml-2 rounded-full bg-blue-500 px-1.5 py-0.5 text-[10px]">{cart.reduce((sum,item)=>sum+item.quantity,0)}</span></Button></div></div>{searchOpen && <div className="mx-auto max-w-7xl pb-4"><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="찾고 싶은 IT 기기를 검색하세요" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-blue-500"/></div>}</header>
    <section id="top" className="mx-auto grid max-w-7xl grid-cols-1 overflow-hidden md:grid-cols-[.85fr_1.15fr]"><div className="bg-[#dfeaf5] px-7 py-20 md:px-16 md:py-32"><p className="mb-6 text-[10px] font-bold tracking-[.24em] text-blue-600">NEXT GENERATION TECHNOLOGY</p><h1 className="text-5xl font-black leading-[.9] tracking-[-.09em] md:text-8xl">일상을 더<br/><span className="font-serif font-normal italic">선명하게.</span></h1><p className="mt-9 max-w-sm text-sm leading-7 text-slate-600">지금 가장 주목받는 테크 브랜드와 새로운 디지털 경험을 한곳에서 만나보세요.</p><a href="#shop" className="mt-10 inline-flex h-28 w-28 items-center justify-center rounded-full bg-blue-600 p-5 text-center text-xs font-bold text-white hover:bg-slate-950">신제품 보기 <ArrowDown className="ml-1" size={16}/></a></div><div className="relative min-h-96"><img className="absolute inset-0 h-full w-full object-cover" src="https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=1500&q=90" alt="최신 IT 기기"/><span className="absolute bottom-5 right-6 text-[10px] font-mono tracking-widest text-white">01 / FUTURE IS NOW</span></div></section>
    <section id="brands" className="mx-auto max-w-7xl px-5 py-16 md:px-10"><p className="mb-5 text-[10px] font-bold tracking-[.2em] text-slate-500">SHOP BY CATEGORY</p><div className="grid grid-cols-2 border-y border-slate-200 md:grid-cols-6">{categories.slice(1,7).map((category, index) => <button key={category} onClick={() => {setSelectedCategory(category); document.querySelector('#shop')?.scrollIntoView({behavior:'smooth'});}} className="border-b border-r border-slate-200 p-5 text-left text-sm font-bold transition hover:bg-blue-600 hover:text-white md:border-b-0"><span className="mb-8 block text-[10px] text-blue-600">0{index+1}</span>{category}<ArrowRight className="float-right" size={15}/></button>)}</div></section>
    <section id="shop" className="mx-auto max-w-7xl px-5 py-20 md:px-10"><div className="mb-10 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-4 text-[10px] font-bold tracking-[.2em] text-blue-600">NEW ARRIVALS</p><h2 className="text-5xl font-black tracking-[-.08em] md:text-7xl">가장 먼저,<br/>새로운 기술.</h2></div><p className="max-w-xs text-sm leading-6 text-slate-600">성능과 디자인, 사용 경험까지 엄격한 기준으로 고른 IT 기기를 소개합니다.</p></div><div className="mb-8 flex gap-2 overflow-auto pb-2">{categories.map(category => <Button key={category} variant={selectedCategory===category?'default':'outline'} size="sm" onClick={() => setSelectedCategory(category)}>{category}</Button>)}</div><div className="grid grid-cols-2 gap-4 md:grid-cols-4 md:gap-5">{visible.map(product => <Card key={product.id} className="group relative border-0 bg-transparent"><button aria-label={`${product.name} 찜하기`} className="absolute right-3 top-3 z-10 grid h-9 w-9 place-items-center rounded-full bg-white/90"><Heart size={17}/></button><a href={`/products/?id=${product.id}`} className="block w-full overflow-hidden rounded-2xl bg-slate-200 text-left"><img className="aspect-[.82] w-full object-cover transition duration-500 group-hover:scale-105" src={product.image} alt={product.name}/></a><div className="py-3"><p className="text-[10px] font-bold tracking-[.16em] text-slate-500">{product.brand}</p><a href={`/products/?id=${product.id}`} className="mt-1 block text-sm font-bold hover:text-blue-600">{product.name}</a><p className="mt-1 text-sm font-semibold">{money(product.price)}</p></div></Card>)}</div></section>
    <section id="story" className="grid bg-slate-950 text-white md:grid-cols-2"><img className="h-96 w-full object-cover md:h-full" src="https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1300&q=85" alt="반도체와 전자 기판"/><div className="px-8 py-24 md:px-20"><p className="mb-6 text-[10px] font-bold tracking-[.2em] text-blue-300">TECH STORY / 08</p><h2 className="text-5xl font-black leading-none tracking-[-.08em] md:text-7xl">좋은 기술은<br/><span className="font-serif font-normal italic">조용히 앞서갑니다.</span></h2><p className="mt-8 max-w-md text-sm leading-7 text-slate-300">복잡한 스펙보다 중요한 것은 매일의 경험입니다. 더 오래 쓰고, 더 편하게 연결되는 기술을 발견해 보세요.</p><a href="#" className="mt-9 inline-flex border-b border-white pb-2 text-sm font-bold">테크 스토리 읽기 <ArrowRight className="ml-4" size={17}/></a></div></section>
    <section id="support" className="bg-blue-600 px-5 py-24 text-white md:px-10"><div className="mx-auto max-w-7xl"><p className="mb-5 text-[10px] font-bold tracking-[.2em] text-blue-100">TECHZONE NEWS</p><h2 className="text-5xl font-black leading-none tracking-[-.08em] md:text-7xl">새로운 기술을<br/>가장 먼저.</h2><form className="mt-12 flex max-w-xl border-b border-blue-300" onSubmit={event=>event.preventDefault()}><input className="w-full bg-transparent py-4 outline-none placeholder:text-blue-200" placeholder="이메일 주소를 입력하세요"/><button className="font-bold">구독하기 <ArrowRight className="ml-2 inline" size={17}/></button></form></div></section>
    {selected && <ProductModal product={selected} onClose={()=>setSelected(null)} onAdd={add}/>}<CartPanel cart={cart} open={cartOpen} total={total} onClose={()=>setCartOpen(false)} onChange={change} onCheckout={placeOrder}/>
  </main>;
}
function ProductModal({product,onClose,onAdd}) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><div className="relative grid max-h-[90vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white md:grid-cols-2"><Button variant="outline" size="icon" className="absolute right-3 top-3 z-10 bg-white" onClick={onClose}><X size={18}/></Button><img className="h-80 w-full object-cover md:h-full" src={product.image} alt={product.name}/><div className="p-8"><p className="text-[10px] font-bold tracking-[.2em] text-blue-600">{product.brand} · {product.category}</p><h2 className="mt-3 text-4xl font-black tracking-[-.08em]">{product.name}</h2><p className="mt-4 text-lg font-bold">{money(product.price)}</p><p className="mt-7 text-sm leading-7 text-slate-600">{product.note}</p><div className="mt-7 flex justify-between border-y border-slate-200 py-4 text-sm"><span className="text-slate-500">색상 / 옵션</span><b>{product.color}</b></div><Button className="mt-6 w-full" onClick={()=>onAdd(product)}>장바구니 담기 <ArrowRight className="ml-2" size={16}/></Button></div></div></div>; }
function CartPanel({cart,open,total,onClose,onChange,onCheckout}) { const [checkout, setCheckout] = useState(false); const [message, setMessage] = useState(''); async function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const order = await onCheckout({ recipient: form.get('recipient'), phone: form.get('phone'), address: form.get('address') }); setMessage(`주문 ${order.orderNumber}이 접수되었습니다.`); setCheckout(false); } catch (error) { setMessage(error.message); } } return <><div className={`fixed inset-0 z-40 bg-slate-950/40 transition ${open?'opacity-100':'pointer-events-none opacity-0'}`} onClick={onClose}/><aside className={`fixed right-0 top-0 z-50 flex h-full w-full max-w-md flex-col bg-white transition-transform ${open?'translate-x-0':'translate-x-full'}`}><div className="flex items-center justify-between border-b p-6"><h2 className="text-xl font-black">{checkout ? '배송 정보' : '장바구니'} <span className="text-sm text-slate-400">{cart.length}</span></h2><Button variant="ghost" size="icon" onClick={onClose}><X size={20}/></Button></div><div className="flex-1 overflow-auto p-6">{checkout ? <form className="grid gap-4" onSubmit={submit}><label className="grid gap-2 text-xs font-bold">받는 분<input required name="recipient" className="rounded-xl border border-slate-200 p-3 font-normal" placeholder="홍길동"/></label><label className="grid gap-2 text-xs font-bold">연락처<input required name="phone" className="rounded-xl border border-slate-200 p-3 font-normal" placeholder="010-0000-0000"/></label><label className="grid gap-2 text-xs font-bold">배송 주소<input required name="address" className="rounded-xl border border-slate-200 p-3 font-normal" placeholder="서울시 ..."/></label><Button type="submit" className="mt-2">{money(total)} 결제하기 <ArrowRight className="ml-2" size={16}/></Button></form> : cart.length ? cart.map(item=><div className="mb-5 grid grid-cols-[84px_1fr] gap-4" key={item.id}><img className="h-24 w-21 rounded-xl object-cover" src={item.image} alt=""/><div><p className="text-[10px] font-bold tracking-wider text-slate-500">{item.brand}</p><h3 className="mt-1 text-sm font-bold">{item.name}</h3><p className="mt-1 text-sm">{money(item.price)}</p><div className="mt-3 flex items-center gap-3"><Button size="sm" variant="outline" onClick={()=>onChange(item.id,-1)}>−</Button><span className="text-sm">{item.quantity}</span><Button size="sm" variant="outline" onClick={()=>onChange(item.id,1)}>+</Button></div></div></div>) : <p className="text-sm text-slate-500">장바구니가 비어 있습니다.</p>}{message && <p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm text-blue-700">{message}</p>}</div>{!checkout && <div className="border-t p-6"><div className="mb-4 flex justify-between font-bold"><span>상품 금액</span><span>{money(total)}</span></div><Button className="w-full" disabled={!cart.length} onClick={()=>setCheckout(true)}>주문하기 <ArrowRight className="ml-2" size={16}/></Button></div>}</aside></>; }
