const { eq, ilike, and, or, desc } = require('drizzle-orm');
const { database } = require('../../shared/db'); const { products } = require('../../shared/schema'); const { server, listen } = require('../../shared/http'); const { publish } = require('../../shared/bus');
const db = database('catalog'); const app = server('catalog');
const seed = [['NOVA Book Air 14','NOVA','노트북',1499000,'하루 종일 이어지는 배터리와 선명한 2.8K 디스플레이.','스페이스 그레이','https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1100&q=85',12],['Orbit Pro X','ORBIT','스마트폰',1199000,'손 안의 강력한 퍼포먼스. 50MP 트리플 카메라.','미드나이트','https://images.unsplash.com/photo-1592899677977-9c10ca588bd?auto=format&fit=crop&w=1100&q=85',18],['Sonic Max ANC','SONIC','오디오',329000,'몰입을 방해하는 소음을 지우는 프리미엄 헤드폰.','크림','https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1100&q=85',20],['Arc Mechanical 75','ARC','게이밍',219000,'정교한 타건감과 자유로운 커스텀을 위한 키보드.','오프화이트','https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1100&q=85',9],['Home Mini Beam','LUMEN','스마트홈',549000,'작은 공간도 영화관으로 만드는 포터블 프로젝터.','오프화이트','https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1100&q=85',14],['Pixel Watch S','PIXEL','웨어러블',399000,'오늘의 컨디션을 가장 정확히 읽는 스마트 워치.','실버','https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1100&q=85',11],['Dock One','NEXA','액세서리',89000,'모든 작업 공간을 하나로 연결하는 멀티 허브.','스페이스 블랙','https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=1100&q=85',23],['Frame 4K','FRAME','게이밍',679000,'144Hz 주사율로 더 빠르고 부드러운 플레이를.','블랙','https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1100&q=85',35]];
async function init() { await db.wait(); await db.query(`CREATE TABLE IF NOT EXISTS products (id UUID PRIMARY KEY,name TEXT NOT NULL,brand TEXT NOT NULL,category TEXT NOT NULL,price INTEGER NOT NULL,note TEXT,color TEXT,image TEXT,stock INTEGER NOT NULL,status TEXT DEFAULT 'published',created_at TIMESTAMPTZ DEFAULT now())`); await db.query("DELETE FROM products WHERE name IN ('Pebble table lamp','No. 04 incense holder','Still life print 01','Soft volume bag','Sunday cup set','Paperweight / cobalt','Wide stripe towel','Index notebook')"); for (const p of seed) { const rows = await db.orm.select({ id: products.id }).from(products).where(eq(products.name, p[0])).limit(1); if (!rows[0]) await db.orm.insert(products).values({ id: crypto.randomUUID(), name: p[0], brand: p[1], category: p[2], price: p[3], note: p[4], color: p[5], image: p[6], stock: p[7], status: 'published' }); } }
app.get('/products', async (req, res) => { const filters = [eq(products.status, 'published')]; if (req.query.category && req.query.category !== 'All') filters.push(eq(products.category, req.query.category)); if (req.query.q) filters.push(or(ilike(products.name, `%${req.query.q}%`), ilike(products.brand, `%${req.query.q}%`))); const rows = await db.orm.select().from(products).where(and(...filters)).orderBy(desc(products.createdAt)); res.json({ items: rows }); });
app.get('/products/:id', async (req, res) => { const rows = await db.orm.select().from(products).where(eq(products.id, req.params.id)).limit(1); rows[0] ? res.json(rows[0]) : res.status(404).json({ code: 'NOT_FOUND' }); });
app.post('/products', async (req, res) => { const p = req.body; const id = crypto.randomUUID(); await db.orm.insert(products).values({ id, ...p }); await publish('product.published', { productId: id }); res.status(201).json({ id }); });
init().then(() => listen(app, 'catalog')).catch(error => { console.error(error); process.exitCode = 1; });
