'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, Plus, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { clearSession, readSession } from '@/lib/session';
const API = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:18080/api';
const won = value => `${new Intl.NumberFormat('ko-KR').format(value)}원`;
export default function ProductManagementPage() {
  const [session, setSession] = useState(undefined); const [products, setProducts] = useState([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  const token = session?.accessToken || session?.token;
  async function load() { if (!token) return; setLoading(true); const response = await fetch(`${API}/products?status=all`, { headers: { authorization: `Bearer ${token}` } }); const data = await response.json(); if (response.status === 401) { clearSession(); setSession(null); throw Error('로그인이 만료되었습니다. 다시 로그인해 주세요.'); } if (!response.ok) throw Error(response.status === 403 ? '관리자 권한이 필요합니다.' : '상품 목록을 불러오지 못했습니다.'); setProducts(data.items || []); setLoading(false); }
  useEffect(() => setSession(readSession()), []); useEffect(() => { load().catch(error => { setMessage(error.message); setLoading(false); }); }, [token]);
  if (session === null || (session && session.user?.role !== 'admin')) return <main className="grid min-h-screen place-items-center bg-slate-100"><div className="rounded-3xl bg-white p-10 text-center"><h1 className="text-2xl font-black">{message || '관리자 로그인이 필요합니다'}</h1><a href="/login/" className="mt-6 inline-block rounded-xl bg-slate-950 px-5 py-3 text-white">로그인</a></div></main>;
  return <main className="min-h-screen bg-[#f4f6fa] p-5 text-slate-950 md:p-10"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><a href="/admin/" className="inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft size={16}/> 대시보드</a><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => load()}><RefreshCw size={14} className="mr-2"/> 새로고침</Button><a href="/admin/products/"><Button size="sm"><Plus size={15} className="mr-2"/> 상품 등록</Button></a></div></div><header className="py-12"><p className="text-[10px] font-bold tracking-[.24em] text-blue-600">CATALOG MANAGEMENT</p><h1 className="mt-4 text-5xl font-black">상품 목록.</h1><p className="mt-4 text-sm text-slate-500">상품 목록과 판매 상태를 먼저 확인한 뒤 상품을 등록하거나 수정합니다.</p></header>{message && <p role="alert" className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{message}</p>}{loading ? <p className="rounded-2xl bg-white p-8">상품을 불러오는 중…</p> : <section className="overflow-x-auto rounded-3xl bg-white p-6"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b text-xs text-slate-400"><tr><th className="pb-3">상품</th><th className="pb-3">브랜드</th><th className="pb-3">카테고리</th><th className="pb-3">가격</th><th className="pb-3">재고</th><th className="pb-3">상태</th><th className="pb-3">관리</th></tr></thead><tbody className="divide-y">{products.map(product => <tr key={product.id}><td className="py-4"><div className="flex items-center gap-3"><img src={product.image} alt="" className="h-12 w-12 rounded-lg object-cover"/><b>{product.name}</b></div></td><td>{product.brand}</td><td>{product.category}</td><td>{won(product.price)}</td><td>{product.stock}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${product.status === 'published' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{product.status}</span></td><td><a href={`/admin/products/?id=${product.id}`} className="font-bold text-blue-600">수정</a></td></tr>)}</tbody></table></section>}</div></main>;
}
