'use client';
import { useEffect, useState } from 'react';
import { ArrowRight, BadgePercent, Clock3, Headphones, PackageCheck, ShieldCheck, Sparkles, Truck, Zap } from 'lucide-react';
import StoreShell, { useStore } from '@/components/store/store-shell';
import ProductCard from '@/components/store/product-card';
import { api, categories, money } from '@techzone/api-client/store';

const benefits: any[] = [[Truck,'8만원 이상 무료배송','빠르고 안전한 배송'],[ShieldCheck,'정품 보증','공식 유통 상품'],[Headphones,'고객 지원','평일 09:00–18:00'],[BadgePercent,'TECHZONE10','최대 5만원 할인']];

export default function Home(){return <StoreShell><HomeContent/></StoreShell>;}
function HomeContent(){
  const [data,setData]=useState(null),[error,setError]=useState('');const {add}=useStore();
  useEffect(()=>{api('/storefront/home').then(setData).catch(()=>setError('스토어 정보를 불러오지 못했습니다.'));},[]);
  if(!data)return <main className="mx-auto max-w-[1440px] px-4 py-10 md:px-8">{error?<p className="rounded-xl bg-red-50 p-5 text-red-700">{error}</p>:<div className="h-[520px] animate-pulse rounded-3xl bg-slate-100"/>}</main>;
  const section=type=>data.sections.find(item=>item.type===type);
  const hero=section('hero'),deal=section('deal'),popular=section('popular'),newItems=section('new'),brand=section('brand'),editorial=section('editorial');
  const heroProduct=hero?.products?.[0];
  const heroPrice=Number(heroProduct?.price||0);
  return <main>
    <section className="bg-slate-950 text-white"><div className="mx-auto grid max-w-[1440px] overflow-hidden lg:min-h-[620px] lg:grid-cols-[.95fr_1.05fr]"><div className="flex flex-col justify-center px-6 py-10 md:px-12 md:py-14 lg:px-16"><span className="inline-flex w-fit items-center gap-2 rounded-full bg-cyan-400 px-3 py-1 text-[11px] font-black text-slate-950"><Sparkles size={13}/>{hero?.config?.eyebrow||'TECHZONE SUPER SALE'}</span><h1 className="mt-6 max-w-2xl text-4xl font-black leading-[.95] tracking-[-.07em] sm:text-5xl md:text-7xl">{hero?.title}<br/><span className="text-cyan-300">더 스마트하게.</span></h1><p className="mt-5 max-w-xl leading-7 text-slate-300 md:mt-6">{hero?.subtitle}</p><div className="mt-8 hidden gap-3 text-sm text-slate-300 sm:grid sm:grid-cols-3"><HeroMetric icon={Zap} label="오늘 출고" value="15시 이전"/><HeroMetric icon={PackageCheck} label="검수 완료" value="정품 유통"/><HeroMetric icon={BadgePercent} label="쿠폰" value="TECHZONE10"/></div><div className="mt-7 flex flex-wrap gap-3 md:mt-9"><a href="/shop/?sort=discount" className="inline-flex items-center rounded-xl bg-cyan-300 px-6 py-4 text-sm font-black text-slate-950 hover:bg-cyan-200">특가 상품 보기 <ArrowRight className="ml-2" size={16}/></a><a href="/shop/" className="rounded-xl border border-white/20 px-6 py-4 text-sm font-black text-white hover:bg-white/10">전체 상품</a></div></div><div className="relative min-h-[430px] bg-slate-900 md:min-h-[430px]"><img src={heroProduct?.image} alt={heroProduct?.name||'TECHZONE 대표 상품'} className="absolute inset-0 h-full w-full object-cover opacity-90"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/10 to-transparent"/>{heroProduct&&<div className="absolute inset-x-4 bottom-32 rounded-2xl border border-white/15 bg-white/95 p-5 text-slate-950 shadow-2xl backdrop-blur md:inset-x-8 md:bottom-8"><p className="text-xs font-black tracking-[.18em] text-rose-500">TODAY PICK</p><div className="mt-2 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><b className="block text-xl md:text-2xl">{heroProduct.name}</b><p className="mt-1 text-xs text-slate-500">{heroProduct.brand} · 빠른 배송 가능</p></div><div className="sm:text-right"><p className="text-xs text-slate-400">판매가</p><strong className="text-2xl text-slate-950">{money(heroPrice)}</strong></div></div><a href={`/products/${heroProduct.slug}/`} className="mt-5 inline-flex items-center rounded-lg bg-slate-950 px-4 py-3 text-sm font-black text-white">상품 상세 보기 <ArrowRight className="ml-2" size={16}/></a></div>}</div></div></section>
    <section className="border-b bg-white"><div className="mx-auto grid max-w-[1440px] grid-cols-2 px-4 md:grid-cols-4 md:px-8">{benefits.map(([Icon,title,desc])=><div key={title} className="flex items-center gap-3 border-r p-5 last:border-0"><Icon className="text-cyan-600"/><div><b className="text-sm">{title}</b><p className="text-xs text-slate-400">{desc}</p></div></div>)}</div></section>
    <section className="mx-auto max-w-[1440px] px-4 py-12 md:px-8"><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-black tracking-[.2em] text-cyan-600">SHOP BY DEVICE</p><h2 className="mt-2 text-2xl font-black tracking-[-.04em]">필요한 기기를 빠르게 찾기</h2></div><a href="/shop/" className="hidden text-sm font-bold text-slate-500 hover:text-slate-950 md:inline-flex">전체 카테고리 <ArrowRight className="ml-2" size={16}/></a></div><div className="grid grid-cols-4 gap-3 md:grid-cols-7">{categories.map((item,index)=><a key={item.slug} href={`/categories/${item.slug}/`} className="group rounded-2xl border bg-white p-4 text-center transition hover:border-cyan-300 hover:shadow-lg"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-slate-100 text-lg font-black text-cyan-700 group-hover:bg-cyan-50">{String(index+1).padStart(2,'0')}</span><b className="mt-3 block text-xs md:text-sm">{item.name}</b></a>)}</div></section>
    <ProductSection section={deal} icon={<Clock3 size={18}/>} accent onAdd={add}/>
    <ProductSection section={popular} onAdd={add}/>
    {editorial&&<section className="mx-auto max-w-[1440px] px-4 py-10 md:px-8"><div className="grid overflow-hidden rounded-3xl bg-slate-950 text-white md:grid-cols-2"><img src={editorial.products?.[3]?.image||editorial.products?.[0]?.image} className="h-80 w-full object-cover md:h-full" alt=""/><div className="p-10 md:p-16"><p className="text-xs font-black tracking-[.2em] text-indigo-300">TECH EDITORIAL</p><h2 className="mt-5 text-4xl font-black tracking-[-.06em] md:text-6xl">{editorial.title}</h2><p className="mt-6 leading-7 text-slate-300">{editorial.subtitle}</p><a href="/shop/?category=액세서리" className="mt-9 inline-flex border-b pb-2 font-bold">기획전 보기 <ArrowRight className="ml-2"/></a></div></div></section>}
    <ProductSection section={newItems} onAdd={add}/>
    <section className="bg-slate-50"><div className="mx-auto max-w-[1440px] px-4 py-16 md:px-8"><div className="flex items-end justify-between"><div><p className="text-xs font-black tracking-[.2em] text-indigo-600">BRAND ZONE</p><h2 className="mt-3 text-3xl font-black">{brand?.title}</h2></div></div><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4">{data.brands.slice(0,8).map(item=><a href={`/shop/?brand=${item.name}`} key={item.slug} className="grid h-28 place-items-center rounded-2xl border bg-white text-xl font-black tracking-tight hover:border-indigo-400">{item.name}</a>)}</div></div></section>
  </main>;
}
function HeroMetric({icon:Icon,label,value}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-4"><Icon size={17} className="text-cyan-300"/><p className="mt-3 text-[11px] font-bold text-slate-400">{label}</p><b className="mt-1 block text-sm text-white">{value}</b></div>;}
function ProductSection({section,onAdd,accent=false,icon=null}){if(!section)return null;return <section className={accent?'bg-indigo-700 text-white':''}><div className="mx-auto max-w-[1440px] px-4 py-16 md:px-8"><div className="flex items-end justify-between"><div><p className={`flex items-center gap-2 text-xs font-black tracking-[.2em] ${accent?'text-indigo-200':'text-indigo-600'}`}>{icon} CURATED BY TECHZONE</p><h2 className="mt-3 text-3xl font-black md:text-4xl">{section.title}</h2><p className={`mt-2 text-sm ${accent?'text-indigo-200':'text-slate-500'}`}>{section.subtitle}</p></div><a href="/shop/" className="hidden text-sm font-bold md:inline-flex">전체보기 <ArrowRight className="ml-2" size={16}/></a></div><div className={`mt-8 grid grid-cols-2 gap-4 md:grid-cols-4 ${accent?'rounded-3xl bg-white p-4 text-slate-950 md:p-6':''}`}>{section.products.slice(0,4).map(product=><ProductCard key={product.id} product={product} onAdd={onAdd}/>)}</div></div></section>;}
