'use client';
import { useEffect, useState } from 'react';
import { ArrowRight, BadgePercent, Clock3, Headphones, ShieldCheck, Truck } from 'lucide-react';
import StoreShell, { useStore } from '@/components/store/store-shell';
import ProductCard from '@/components/store/product-card';
import { api, categories } from '@techzone/api-client/store';

const benefits: any[] = [[Truck,'8만원 이상 무료배송','빠르고 안전한 배송'],[ShieldCheck,'정품 보증','공식 유통 상품'],[Headphones,'고객 지원','평일 09:00–18:00'],[BadgePercent,'TECHZONE10','최대 5만원 할인']];

export default function Home(){return <StoreShell><HomeContent/></StoreShell>;}
function HomeContent(){
  const [data,setData]=useState(null),[error,setError]=useState('');const {add}=useStore();
  useEffect(()=>{api('/storefront/home').then(setData).catch(()=>setError('스토어 정보를 불러오지 못했습니다.'));},[]);
  if(!data)return <main className="mx-auto max-w-[1440px] px-4 py-10 md:px-8">{error?<p className="rounded-xl bg-red-50 p-5 text-red-700">{error}</p>:<div className="h-[520px] animate-pulse rounded-3xl bg-slate-100"/>}</main>;
  const section=type=>data.sections.find(item=>item.type===type);
  const hero=section('hero'),deal=section('deal'),popular=section('popular'),newItems=section('new'),brand=section('brand'),editorial=section('editorial');
  return <main>
    <section className="bg-[#eef0ff]"><div className="mx-auto grid max-w-[1440px] overflow-hidden md:min-h-[540px] md:grid-cols-[.9fr_1.1fr]"><div className="flex flex-col justify-center px-6 py-16 md:px-16"><span className="w-fit rounded-full bg-indigo-100 px-3 py-1 text-[11px] font-black text-indigo-700">{hero?.config?.eyebrow||'TECHZONE SUPER SALE'}</span><h1 className="mt-6 text-5xl font-black leading-[.95] tracking-[-.07em] md:text-7xl">{hero?.title}<br/><span className="text-indigo-600">더 스마트하게.</span></h1><p className="mt-6 max-w-lg leading-7 text-slate-600">{hero?.subtitle}</p><div className="mt-9 flex gap-3"><a href="/shop/?sort=discount" className="rounded-xl bg-indigo-600 px-6 py-4 text-sm font-black text-white">특가 상품 보기</a><a href="/shop/" className="rounded-xl border border-slate-300 bg-white px-6 py-4 text-sm font-black">전체 상품</a></div></div><div className="relative min-h-96"><img src={hero?.products?.[0]?.image} alt="" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute bottom-6 left-6 rounded-2xl bg-white/95 p-5 shadow-xl"><p className="text-xs font-bold text-slate-400">오늘만 이 가격</p><b className="mt-1 block text-lg">{hero?.products?.[0]?.name}</b><a href={`/products/${hero?.products?.[0]?.slug}/`} className="mt-2 inline-flex text-sm font-black text-indigo-600">보러 가기 <ArrowRight size={16}/></a></div></div></div></section>
    <section className="border-b bg-white"><div className="mx-auto grid max-w-[1440px] grid-cols-2 px-4 md:grid-cols-4 md:px-8">{benefits.map(([Icon,title,desc])=><div key={title} className="flex items-center gap-3 border-r p-5 last:border-0"><Icon className="text-indigo-600"/><div><b className="text-sm">{title}</b><p className="text-xs text-slate-400">{desc}</p></div></div>)}</div></section>
    <section className="mx-auto max-w-[1440px] px-4 py-12 md:px-8"><div className="grid grid-cols-4 gap-3 md:grid-cols-7">{categories.map((item,index)=><a key={item.slug} href={`/categories/${item.slug}/`} className="group rounded-2xl border bg-white p-4 text-center hover:border-indigo-300 hover:shadow-lg"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-slate-100 text-lg font-black text-indigo-600">{String(index+1).padStart(2,'0')}</span><b className="mt-3 block text-xs md:text-sm">{item.name}</b></a>)}</div></section>
    <ProductSection section={deal} icon={<Clock3 size={18}/>} accent onAdd={add}/>
    <ProductSection section={popular} onAdd={add}/>
    {editorial&&<section className="mx-auto max-w-[1440px] px-4 py-10 md:px-8"><div className="grid overflow-hidden rounded-3xl bg-slate-950 text-white md:grid-cols-2"><img src={editorial.products?.[3]?.image||editorial.products?.[0]?.image} className="h-80 w-full object-cover md:h-full" alt=""/><div className="p-10 md:p-16"><p className="text-xs font-black tracking-[.2em] text-indigo-300">TECH EDITORIAL</p><h2 className="mt-5 text-4xl font-black tracking-[-.06em] md:text-6xl">{editorial.title}</h2><p className="mt-6 leading-7 text-slate-300">{editorial.subtitle}</p><a href="/shop/?category=액세서리" className="mt-9 inline-flex border-b pb-2 font-bold">기획전 보기 <ArrowRight className="ml-2"/></a></div></div></section>}
    <ProductSection section={newItems} onAdd={add}/>
    <section className="bg-slate-50"><div className="mx-auto max-w-[1440px] px-4 py-16 md:px-8"><div className="flex items-end justify-between"><div><p className="text-xs font-black tracking-[.2em] text-indigo-600">BRAND ZONE</p><h2 className="mt-3 text-3xl font-black">{brand?.title}</h2></div></div><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4">{data.brands.slice(0,8).map(item=><a href={`/shop/?brand=${item.name}`} key={item.slug} className="grid h-28 place-items-center rounded-2xl border bg-white text-xl font-black tracking-tight hover:border-indigo-400">{item.name}</a>)}</div></div></section>
  </main>;
}
function ProductSection({section,onAdd,accent=false,icon=null}){if(!section)return null;return <section className={accent?'bg-indigo-700 text-white':''}><div className="mx-auto max-w-[1440px] px-4 py-16 md:px-8"><div className="flex items-end justify-between"><div><p className={`flex items-center gap-2 text-xs font-black tracking-[.2em] ${accent?'text-indigo-200':'text-indigo-600'}`}>{icon} CURATED BY TECHZONE</p><h2 className="mt-3 text-3xl font-black md:text-4xl">{section.title}</h2><p className={`mt-2 text-sm ${accent?'text-indigo-200':'text-slate-500'}`}>{section.subtitle}</p></div><a href="/shop/" className="hidden text-sm font-bold md:inline-flex">전체보기 <ArrowRight className="ml-2" size={16}/></a></div><div className={`mt-8 grid grid-cols-2 gap-4 md:grid-cols-4 ${accent?'rounded-3xl bg-white p-4 text-slate-950 md:p-6':''}`}>{section.products.slice(0,4).map(product=><ProductCard key={product.id} product={product} onAdd={onAdd}/>)}</div></div></section>;}
