'use client';
import { useEffect, useState } from 'react';
import { ArrowRight, Check, CreditCard, Landmark, LockKeyhole, MessageCircle, PackageCheck, ShieldCheck, TicketPercent } from 'lucide-react';
import StoreShell, { useStore } from '@/components/store/store-shell';
import { api, money, optionText } from '@techzone/api-client/store';
import { getCurrentUserId, readSession } from '@techzone/api-client/session';

const methods: any[]=[['card','신용·체크카드',CreditCard],['kakaopay','카카오페이',MessageCircle],['naverpay','네이버페이',Check],['bank','무통장입금',Landmark]];
export default function Page(){return <StoreShell><Checkout/></StoreShell>;}
function Checkout(){
  const{cart,total}=useStore();const[quote,setQuote]=useState(null),[coupon,setCoupon]=useState(''),[method,setMethod]=useState('card'),[loading,setLoading]=useState(false),[message,setMessage]=useState('');const session=typeof window==='undefined'?null:readSession();
  const lines=cart.map(item=>({variantId:item.variant_id,quantity:item.quantity}));
  const lineKey=JSON.stringify(lines);
  useEffect(()=>{setQuote(null);if(lines.length)loadQuote('');},[lineKey]);
  async function loadQuote(code){try{setQuote(await api('/checkout/quote',{method:'POST',body:JSON.stringify({items:lines,couponCode:code||undefined})}));setMessage(code?'쿠폰이 적용되었습니다.':'');}catch(error){setQuote(null);setMessage(({INVALID_COUPON:'사용할 수 없는 쿠폰입니다.',COUPON_MIN_ORDER:'30만원 이상 구매 시 사용할 수 있습니다.',INSUFFICIENT_STOCK:'선택한 옵션의 재고가 부족합니다. 장바구니 수량을 조정해 주세요.',INVENTORY_UNAVAILABLE:'재고를 확인하지 못했습니다. 잠시 후 다시 시도해 주세요.'})[error.message]||'견적을 계산하지 못했습니다.');}}
  async function submit(event){event.preventDefault();if(!quote)return;setLoading(true);setMessage('');const form=new FormData(event.currentTarget);try{const userId=getCurrentUserId();const order=await api('/orders',{method:'POST',body:JSON.stringify({userId,quoteToken:quote.quoteToken,guestOrder:!session,paymentMethod:method,shipping:{recipient:form.get('recipient'),phone:form.get('phone'),postalCode:form.get('postalCode'),address:form.get('address'),address2:form.get('address2'),memo:form.get('memo')}})});await api('/payments/confirm',{method:'POST',body:JSON.stringify({orderId:order.id,amount:order.totalAmount,method,paymentKey:`${method}_${order.id}`,order:{userId,items:quote.lines}})});await api(`/carts/${userId}`,{method:'DELETE'});if(order.guestOrderToken)localStorage.setItem(`techzone-guest-order-${order.orderNumber}`,order.guestOrderToken);const mobile=process.env.NEXT_PUBLIC_RUNTIME==='capacitor';location.href=mobile?`/order-complete/?number=${order.orderNumber}&id=${order.id}`:`/order-complete/${order.orderNumber}/?id=${order.id}`;}catch(error){setMessage(error.message==='PRICE_CHANGED'?'상품 가격이 변경되었습니다. 견적을 다시 확인해 주세요.':error.message==='INSUFFICIENT_STOCK'?'결제 중 재고가 변경되었습니다. 장바구니 수량을 다시 확인해 주세요.':'주문 처리에 실패했습니다.');setLoading(false);}}
  if(!cart.length)return <main className="mx-auto max-w-4xl p-10 text-center"><h1 className="text-2xl font-black">주문할 상품이 없습니다.</h1><a href="/shop/" className="mt-6 inline-block text-indigo-600">상품 보러 가기</a></main>;
  return <main className="mx-auto max-w-6xl px-4 py-10 md:px-8"><p className="text-xs font-black tracking-[.2em] text-cyan-600">CHECKOUT</p><h1 className="mt-2 text-4xl font-black tracking-[-.06em]">주문/결제</h1><div className="mt-3 flex items-center gap-2 text-sm text-slate-500"><span>01 장바구니</span><ArrowRight size={14}/><span className="font-bold text-cyan-600">02 주문/결제</span><ArrowRight size={14}/><span>03 완료</span></div>{!session&&<div className="mt-6 flex gap-3 rounded-2xl border border-cyan-100 bg-cyan-50 p-4 text-sm text-cyan-900"><PackageCheck size={20}/><p><b>비회원 주문으로 진행합니다.</b><span className="mt-1 block text-xs text-cyan-800">주문 완료 후 주문번호와 휴대폰 번호로 배송 조회, 취소, 반품 요청을 할 수 있습니다.</span></p></div>}<form onSubmit={submit} className="mt-10 grid gap-8 lg:grid-cols-[1fr_400px]"><div className="grid gap-6"><Box title="주문 상품">{cart.map(item=><article key={item.variant_id} className="flex gap-4 border-b py-4 last:border-0"><img src={item.image} className="h-20 w-20 rounded-xl object-cover" alt=""/><div><b className="text-sm">{item.name}</b><p className="mt-1 text-xs text-slate-400">{optionText(item.option_values)} · {item.quantity}개</p><strong className="mt-2 block text-sm">{money(Number(item.price)*item.quantity)}</strong></div></article>)}</Box>
    <Box title="배송 정보"><div className="grid gap-4 md:grid-cols-2"><Input name="recipient" label="받는 분" defaultValue={session?.user?.name}/><Input name="phone" label="휴대폰 번호" placeholder="010-0000-0000"/><Input name="postalCode" label="우편번호" placeholder="06134"/><div/><Input name="address" label="주소" className="md:col-span-2"/><Input name="address2" label="상세 주소" className="md:col-span-2"/><Input name="memo" label="배송 메모" required={false} className="md:col-span-2"/></div></Box>
    <Box title="쿠폰"><div className="flex gap-2"><input value={coupon} onChange={e=>setCoupon(e.target.value.toUpperCase())} className="flex-1 rounded-xl border p-3" placeholder="쿠폰 코드"/><button type="button" onClick={()=>loadQuote(coupon)} className="rounded-xl border border-cyan-600 px-5 text-sm font-bold text-cyan-700">적용</button></div><div className="mt-3 flex gap-2 rounded-xl bg-rose-50 p-4 text-xs text-rose-700"><TicketPercent size={16}/><span><b>TECHZONE10</b> · 30만원 이상 10%, 최대 5만원 할인</span></div></Box>
    <Box title="결제 수단"><div className="grid grid-cols-2 gap-3">{methods.map(([key,label,Icon])=><button type="button" onClick={()=>setMethod(key)} key={key} className={`flex items-center gap-3 rounded-xl border p-4 text-sm font-bold ${method===key?'border-slate-950 bg-slate-950 text-white':'hover:border-cyan-300'}`}><Icon size={19}/>{label}</button>)}</div><p className="mt-4 flex gap-2 text-xs text-slate-400"><ShieldCheck size={15}/> 포트폴리오 환경에서는 안전한 Mock 결제로 승인됩니다.</p></Box></div>
    <aside className="h-fit rounded-3xl border bg-white p-6 shadow-sm lg:sticky lg:top-36"><h2 className="text-xl font-black">최종 결제 금액</h2><dl className="mt-6 grid gap-4 text-sm"><Row label="상품 금액" value={money(quote?.subtotalAmount||total)}/><Row label="상품 할인" value={`-${money(quote?.discountAmount||0)}`} accent/><Row label="배송비" value={quote?.shippingFee?money(quote.shippingFee):'무료'}/><Row label="총 결제 금액" value={money(quote?.totalAmount||total)} total/></dl><div className="mt-5 grid gap-2 rounded-2xl bg-slate-50 p-4 text-xs text-slate-500"><p className="flex items-center gap-2"><LockKeyhole size={15}/> 가격 변경 시 주문 생성 전에 자동 차단됩니다.</p><p className="flex items-center gap-2"><ShieldCheck size={15}/> 주문·결제·재고 예약은 서버에서 다시 검증합니다.</p></div><label className="mt-4 flex gap-2 rounded-xl bg-cyan-50 p-4 text-xs leading-5 text-cyan-900"><input required type="checkbox"/>주문 상품, 가격, 배송 정보 및 개인정보 수집·이용에 동의합니다.</label>{message&&<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-700">{message}</p>}<button disabled={loading||!quote} className="mt-5 h-14 w-full rounded-xl bg-slate-950 font-black text-white disabled:opacity-50">{loading?'결제 처리 중...':`${money(quote?.totalAmount||total)} 결제하기`}</button></aside></form></main>;
}
function Box({title,children}){return <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">{title}</h2><div className="mt-5">{children}</div></section>;}
function Input({label,className='',required=true,...props}){return <label className={`grid gap-2 text-xs font-bold ${className}`}>{label}<input required={required} {...props} className="rounded-xl border p-3 text-sm font-normal"/></label>;}
function Row({label,value,accent=false,total=false}){return <div className={`flex justify-between ${total?'border-t pt-5 text-xl font-black':''}`}><dt>{label}</dt><dd className={accent?'text-rose-500':total?'text-cyan-700':''}>{value}</dd></div>;}
