'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { clearSession, readSession } from '@/lib/session';
import { createColumnHelper } from '@tanstack/react-table';
import DataTable from './data-table';
const API=process.env.NEXT_PUBLIC_API_BASE_URL||'http://localhost:18080/api'; const labels={inventory:'재고관리',orders:'주문관리',shipping:'배송관리',reviews:'리뷰관리',members:'회원관리'}; const statusLabels={pending:'결제 대기',confirmed:'주문 확정',preparing:'상품 준비',shipped:'배송 중',delivered:'배송 완료',cancelled:'주문 취소'};
export default function Operations({type}){const[s,setS]=useState(undefined);const[data,setData]=useState({});const[msg,setMsg]=useState('');const token=s?.accessToken||s?.token;async function load(){if(!token)return;const path=type==='members'?'auth/users':type==='reviews'?'reviews':type==='inventory'?'inventory':'orders';const r=await fetch(`${API}/${path}`,{headers:{authorization:`Bearer ${token}`}});const d=await r.json();if(r.status===401){clearSession();setS(null);throw Error('로그인이 만료되었습니다.')}if(!r.ok)throw Error('데이터를 불러오지 못했습니다.');setData(d)}useEffect(()=>setS(readSession()),[]);useEffect(()=>{load().catch(e=>setMsg(e.message))},[token]);if(s===null||(s&&s.user?.role!=='admin'))return <main className="grid min-h-screen place-items-center bg-slate-100"><div className="rounded-3xl bg-white p-10 text-center"><h1 className="text-2xl font-black">관리자 로그인이 필요합니다</h1><a href="/login/" className="mt-6 inline-block rounded-xl bg-slate-950 px-5 py-3 text-white">로그인</a></div></main>;return <main className="min-h-screen bg-[#f4f6fa] p-5 md:p-10"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><a href="/admin/" className="inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft size={16}/> 대시보드</a><Button variant="outline" size="sm" onClick={load}><RefreshCw size={14} className="mr-2"/> 새로고침</Button></div><header className="py-12"><p className="text-[10px] font-bold tracking-[.24em] text-blue-600">TECHZONE OPERATIONS</p><h1 className="mt-4 text-5xl font-black">{labels[type]}.</h1><p className="mt-4 text-sm text-slate-500">운영 데이터와 처리 상태를 관리합니다.</p></header>{msg&&<p role="alert" className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{msg}</p>}<Content type={type} data={data}/></div></main>}
function Content({type,data}){const h=createColumnHelper();if(type==='inventory')return <DataTable data={data.items||[]} placeholder="상품 ID 검색" columns={[h.accessor('product_id',{header:'상품 ID'}),h.accessor('available_qty',{header:'가용 재고'}),h.accessor('version',{header:'버전'})]}/>;if(type==='members')return <DataTable data={data.items||[]} placeholder="이름·이메일 검색" columns={[h.accessor('name',{header:'이름'}),h.accessor('email',{header:'이메일'}),h.accessor('role',{header:'권한'}),h.accessor('createdAt',{header:'가입일',cell:i=>new Date(i.getValue()).toLocaleDateString('ko-KR')})]}/>;if(type==='reviews')return <DataTable data={data.items||[]} placeholder="작성자·리뷰 내용 검색" columns={[h.accessor('user_name',{header:'작성자'}),h.accessor('rating',{header:'평점',cell:i=>`★ ${i.getValue()}`}),h.accessor('body',{header:'내용'}),h.accessor('status',{header:'상태'})]}/>;return <DataTable data={data.items||[]} placeholder="주문번호·받는 분 검색" columns={[h.accessor('order_number',{header:'주문번호'}),h.accessor('recipient',{header:'받는 분'}),h.accessor('total_amount',{header:'금액',cell:i=>`${new Intl.NumberFormat('ko-KR').format(i.getValue())}원`}),h.accessor('status',{header:'상태',cell:i=><span className="rounded-full bg-indigo-50 px-2 py-1 text-xs font-bold text-indigo-700">{statusLabels[i.getValue()]||i.getValue()}</span>})]}/>}
function Table({headers,children}){return <section className="overflow-x-auto rounded-3xl bg-white p-6"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b text-xs text-slate-400"><tr>{headers.map(x=><th className="pb-3" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{children}</tbody></table></section>}
