'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { SlidersHorizontal, X } from 'lucide-react';
import StoreShell, { useStore } from './store-shell';
import ProductCard from './product-card';
import { api, categories, money } from '@techzone/api-client/store';

export default function ShopView({initialCategory='',initialData=null,initialBrands=[]}){return <StoreShell><ShopContent initialCategory={initialCategory} initialData={initialData} initialBrands={initialBrands}/></StoreShell>;}
function ShopContent({initialCategory,initialData,initialBrands}){
  const [filters,setFilters]=useState({q:'',category:initialCategory,brand:'',minPrice:'',maxPrice:'',inStock:false,discounted:false,sort:'popular',page:1}),[data,setData]=useState(initialData||{items:[],total:0,pageCount:1}),[loading,setLoading]=useState(!initialData),[error,setError]=useState(''),[filterOpen,setFilterOpen]=useState(false),[brands,setBrands]=useState(initialBrands);const {add}=useStore();const skipInitialFetch=useRef(Boolean(initialData));
  useEffect(()=>{const p=new URLSearchParams(location.search);const next={q:p.get('q')||'',category:initialCategory||p.get('category')||'',brand:p.get('brand')||'',minPrice:p.get('minPrice')||'',maxPrice:p.get('maxPrice')||'',inStock:p.get('inStock')==='true',discounted:p.get('discounted')==='true',sort:p.get('sort')||'popular',page:Number(p.get('page')||1)};setFilters(current=>Object.keys(next).every(key=>current[key]===next[key])?current:next);if(!initialBrands.length)api('/storefront/home').then(v=>setBrands(v.brands||[])).catch(()=>{});},[initialCategory,initialBrands]);
  useEffect(()=>{if(skipInitialFetch.current){skipInitialFetch.current=false;return;}const p=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>{if(v&&k!=='page')p.set(k,String(v));});p.set('page',String(filters.page));history.replaceState(null,'',`${location.pathname}?${p}`);setLoading(true);setError('');api(`/products?${p}&pageSize=20`).then(setData).catch(()=>setError('상품 목록을 불러오지 못했습니다.')).finally(()=>setLoading(false));},[filters]);
  const categoryName=categories.find(item=>item.slug===filters.category)?.name||filters.category;
  return <main className="mx-auto max-w-[1440px] px-4 py-8 md:px-8"><div className="text-xs text-slate-600">홈 / {categoryName||'전체 상품'}</div><header className="mt-6 border-b pb-8"><h1 className="text-4xl font-black tracking-[-.06em]">{categoryName||'전체 상품'}</h1><p className="mt-2 text-sm text-slate-500">검증된 테크 상품 {data.total}개를 만나보세요.</p></header>
    <div className="mt-6 flex items-center justify-between"><button className="flex items-center gap-2 rounded-lg border px-4 py-2 text-sm font-bold md:hidden" onClick={()=>setFilterOpen(true)}><SlidersHorizontal size={16}/> 필터</button><span className="hidden text-sm text-slate-500 md:block">총 <b className="text-slate-950">{data.total}</b>개</span><select aria-label="상품 정렬" value={filters.sort} onChange={e=>setFilters(v=>({...v,sort:e.target.value,page:1}))} className="rounded-lg border px-3 py-2 text-sm"><option value="popular">인기순</option><option value="newest">신상품순</option><option value="discount">할인율순</option><option value="price_asc">낮은 가격순</option><option value="price_desc">높은 가격순</option></select></div>
    <div className="mt-6 grid gap-8 md:grid-cols-[240px_1fr]"><FilterPanel open={filterOpen} filters={filters} brands={brands} onClose={()=>setFilterOpen(false)} onChange={(key,value)=>setFilters(v=>({...v,[key]:value,page:1}))}/><section>{loading?<div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="aspect-[.8] animate-pulse rounded-2xl bg-slate-100"/>)}</div>:error?<div role="alert" className="rounded-2xl bg-red-50 py-24 text-center text-red-800"><p className="font-bold">{error}</p><button onClick={()=>setFilters(v=>({...v}))} className="mt-4 text-sm font-bold underline">다시 시도</button></div>:data.items.length?<div className="grid grid-cols-2 gap-x-4 gap-y-10 lg:grid-cols-4">{data.items.map((product,index)=><ProductCard key={product.id} product={product} onAdd={add} priority={index<2}/>)}</div>:<div className="rounded-2xl bg-slate-50 py-24 text-center"><p className="font-bold">조건에 맞는 상품이 없습니다.</p><button onClick={()=>setFilters({q:'',category:'',brand:'',minPrice:'',maxPrice:'',inStock:false,discounted:false,sort:'popular',page:1})} className="mt-4 text-sm font-bold text-indigo-600">필터 초기화</button></div>}
      <div className="mt-12 flex justify-center gap-2">{Array.from({length:data.pageCount},(_,i)=>i+1).slice(0,10).map(page=><button key={page} onClick={()=>setFilters(v=>({...v,page}))} className={`h-10 w-10 rounded-lg text-sm font-bold ${filters.page===page?'bg-indigo-600 text-white':'border'}`}>{page}</button>)}</div></section></div>
  </main>;
}
function FilterPanel({open,filters,brands,onClose,onChange}){return <aside className={`fixed inset-y-0 left-0 z-50 w-80 overflow-auto bg-white p-6 shadow-2xl transition md:static md:z-auto md:w-auto md:p-0 md:shadow-none ${open?'translate-x-0':'-translate-x-full md:translate-x-0'}`}><div className="flex justify-between md:hidden"><b>상세 필터</b><button aria-label="상세 필터 닫기" onClick={onClose}><X/></button></div><div className="mt-6 md:mt-0"><Filter title="카테고리">{categories.map(item=><label key={item.slug} className="flex gap-2 py-1.5 text-sm"><input type="radio" checked={filters.category===item.slug||filters.category===item.name} onChange={()=>onChange('category',item.slug)}/>{item.name}</label>)}</Filter><Filter title="브랜드"><select aria-label="브랜드 필터" value={filters.brand} onChange={e=>onChange('brand',e.target.value)} className="w-full rounded-lg border p-2 text-sm"><option value="">전체 브랜드</option>{brands.map(item=><option key={item.slug}>{item.name}</option>)}</select></Filter><Filter title="가격대"><div className="grid grid-cols-2 gap-2"><input aria-label="최소 가격" type="number" value={filters.minPrice} onChange={e=>onChange('minPrice',e.target.value)} className="min-w-0 rounded-lg border p-2 text-xs" placeholder="최소"/><input aria-label="최대 가격" type="number" value={filters.maxPrice} onChange={e=>onChange('maxPrice',e.target.value)} className="min-w-0 rounded-lg border p-2 text-xs" placeholder="최대"/></div><p className="mt-2 text-xs text-slate-600">{filters.minPrice&&money(filters.minPrice)} {filters.maxPrice&&`– ${money(filters.maxPrice)}`}</p></Filter><div className="border-b py-4"><label className="flex gap-2 py-1.5 text-sm font-bold"><input type="checkbox" checked={filters.discounted} onChange={e=>onChange('discounted',e.target.checked)}/>할인 상품만</label><label className="flex gap-2 py-1.5 text-sm font-bold"><input type="checkbox" checked={filters.inStock} onChange={e=>onChange('inStock',e.target.checked)}/>품절 상품 제외</label></div></div></aside>;}
function Filter({title,children}){return <section className="border-b py-5"><h2 className="mb-3 text-sm font-black">{title}</h2>{children}</section>;}
