'use client';
import { useEffect, useMemo, useState } from 'react';
import { Check, ChevronRight, Heart, Minus, Plus, ShieldCheck, ShoppingBag, Star, Truck } from 'lucide-react';
import StoreShell, { useStore } from './store-shell';
import ProductCard from './product-card';
import { api, money, optionText } from '@/lib/store';
import { readSession } from '@/lib/session';

export default function ProductDetailView({slug,id}){return <StoreShell><ProductDetail slug={slug} id={id}/></StoreShell>;}
function ProductDetail({slug,id}){
  const [product,setProduct]=useState(null),[error,setError]=useState(''),[variantId,setVariantId]=useState(''),[image,setImage]=useState(''),[quantity,setQuantity]=useState(1),[tab,setTab]=useState('detail'),[wish,setWish]=useState(false),[notice,setNotice]=useState('');const {add}=useStore();
  useEffect(()=>{api(slug?`/products/by-slug/${slug}`:`/products/${id}`).then(data=>{setProduct(data);setVariantId(data.variants?.[0]?.id||'');setImage(data.images?.[0]?.url||data.image);const recent=JSON.parse(localStorage.getItem('techzone-recent')||'[]').filter(value=>value.id!==data.id);localStorage.setItem('techzone-recent',JSON.stringify([{id:data.id,slug:data.slug,name:data.name,image:data.image,price:data.price},...recent].slice(0,8)));setWish(JSON.parse(localStorage.getItem('techzone-wishlist')||'[]').includes(data.id));}).catch(()=>setError('상품 정보를 불러오지 못했습니다.'));},[slug,id]);
  const variant=useMemo(()=>product?.variants?.find(item=>item.id===variantId),[product,variantId]);
  function toggleWish(){const values=JSON.parse(localStorage.getItem('techzone-wishlist')||'[]');const next=wish?values.filter(value=>value!==product.id):[...new Set([...values,product.id])];localStorage.setItem('techzone-wishlist',JSON.stringify(next));setWish(!wish);const session=readSession();if(session)api(`/wishlists/${session.user.id}/${product.id}`,{method:wish?'DELETE':'POST',headers:{authorization:`Bearer ${session.accessToken||session.token}`}}).catch(()=>{});}
  async function cart(buy=false){await add(product,variant,quantity);setNotice('장바구니에 담았습니다.');if(buy)location.href='/checkout/';}
  async function ask(event){event.preventDefault();const session=readSession();if(!session){location.href='/login/';return;}const form=new FormData(event.currentTarget);await api(`/products/${product.id}/questions`,{method:'POST',headers:{authorization:`Bearer ${session.accessToken||session.token}`},body:JSON.stringify({title:form.get('title'),body:form.get('body')})});setNotice('문의가 등록되었습니다.');event.currentTarget.reset();}
  async function review(event){event.preventDefault();const session=readSession();if(!session){location.href='/login/';return;}const form=new FormData(event.currentTarget);try{await api(`/products/${product.id}/reviews`,{method:'POST',headers:{authorization:`Bearer ${session.accessToken||session.token}`},body:JSON.stringify({rating:Number(form.get('rating')),body:form.get('body')})});setNotice('리뷰가 등록되어 검수 대기 중입니다.');event.currentTarget.reset();}catch(error){setNotice(error.message==='PURCHASE_REQUIRED'?'배송 완료된 구매 상품만 리뷰를 작성할 수 있습니다.':'리뷰를 등록하지 못했습니다.');}}
  if(error)return <main className="mx-auto max-w-4xl p-10"><p className="rounded-xl bg-red-50 p-6 text-red-700">{error}</p></main>;
  if(!product)return <main className="mx-auto max-w-[1440px] p-8"><div className="h-[600px] animate-pulse rounded-3xl bg-slate-100"/></main>;
  const price=variant?.salePrice||product.price,listPrice=variant?.listPrice||product.listPrice,discount=Math.round((listPrice-price)*100/listPrice);
  return <main className="mx-auto max-w-[1440px] px-4 py-8 md:px-8"><div className="flex items-center gap-2 text-xs text-slate-400">홈 <ChevronRight size={12}/> {product.category} <ChevronRight size={12}/> {product.name}</div>
    <section className="mt-8 grid gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><div className="overflow-hidden rounded-3xl bg-slate-100"><img src={image} alt={product.name} className="aspect-square w-full object-cover"/></div><div className="mt-3 grid grid-cols-5 gap-2">{product.images.map(item=><button key={item.id} onClick={()=>setImage(item.url)} className={`overflow-hidden rounded-xl border-2 ${image===item.url?'border-indigo-600':'border-transparent'}`}><img src={item.url} alt={item.alt} className="aspect-square object-cover"/></button>)}</div></div>
      <div className="lg:sticky lg:top-36 lg:self-start"><p className="text-xs font-black tracking-[.2em] text-indigo-600">{product.brand}</p><h1 className="mt-3 text-4xl font-black tracking-[-.06em] md:text-5xl">{product.name}</h1><div className="mt-4 flex items-center gap-2 text-sm"><Star size={16} className="fill-amber-400 text-amber-400"/><b>{product.reviewSummary.average||0}</b><button onClick={()=>setTab('reviews')} className="text-slate-500">리뷰 {product.reviewSummary.count}개</button></div><p className="mt-5 text-slate-600">{product.note}</p>
        <div className="mt-7 border-y py-6"><del className="text-sm text-slate-400">{money(listPrice)}</del><div className="mt-1 flex items-baseline gap-3"><b className="text-2xl text-rose-500">{discount}%</b><strong className="text-3xl">{money(price)}</strong></div><p className="mt-2 text-xs text-slate-400">부가세 포함 · 카드사 무이자 할부 가능</p></div>
        <div className="mt-6"><b className="text-sm">옵션 선택</b><div className="mt-3 grid gap-2">{product.variants.map(item=><button key={item.id} onClick={()=>setVariantId(item.id)} className={`flex items-center justify-between rounded-xl border p-4 text-left ${variantId===item.id?'border-indigo-600 bg-indigo-50 ring-1 ring-indigo-600':'border-slate-200'}`}><span><b className="text-sm">{optionText(item.optionValues)}</b><small className="mt-1 block text-slate-400">{item.sku}</small></span><strong>{money(item.salePrice)}</strong></button>)}</div></div>
        <div className="mt-5 grid gap-3 rounded-2xl bg-slate-50 p-5 text-sm"><p className="flex gap-3"><Truck className="text-indigo-600" size={19}/><span><b>내일 도착 예정</b><small className="block text-slate-400">평일 오후 2시 이전 결제 시</small></span></p><p className="flex gap-3"><ShieldCheck className="text-indigo-600" size={19}/><span><b>정품 보증 · 안전 포장</b><small className="block text-slate-400">TECHZONE 공식 유통 상품</small></span></p></div>
        <div className="mt-6 flex gap-3"><div className="flex items-center rounded-xl border"><button onClick={()=>setQuantity(Math.max(1,quantity-1))} className="p-4"><Minus size={15}/></button><b className="w-8 text-center">{quantity}</b><button onClick={()=>setQuantity(Math.min(20,quantity+1))} className="p-4"><Plus size={15}/></button></div><button onClick={toggleWish} className={`grid w-14 place-items-center rounded-xl border ${wish?'border-rose-300 bg-rose-50 text-rose-500':''}`}><Heart className={wish?'fill-current':''}/></button><button onClick={()=>cart(false)} className="flex-1 rounded-xl border-2 border-indigo-600 font-black text-indigo-600">장바구니</button><button onClick={()=>cart(true)} className="flex-1 rounded-xl bg-indigo-600 font-black text-white">바로구매</button></div>{notice&&<p className="mt-3 flex items-center gap-2 rounded-lg bg-emerald-50 p-3 text-sm font-bold text-emerald-700"><Check size={16}/>{notice}</p>}
      </div></section>
    <section className="mt-20"><nav className="sticky top-30 z-20 grid grid-cols-4 border-y bg-white">{[['detail','상품정보'],['specs','상세스펙'],['reviews',`리뷰 ${product.reviewSummary.count}`],['questions',`Q&A ${product.questions.length}`]].map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`py-5 text-sm font-black ${tab===key?'border-b-2 border-indigo-600 text-indigo-600':''}`}>{label}</button>)}</nav>
      <div className="mx-auto max-w-4xl py-12">{tab==='detail'&&<div className="prose max-w-none"><h2 className="text-center text-4xl font-black">{product.name}</h2><div className="mt-8 rounded-3xl bg-slate-50 p-8 text-center leading-8" dangerouslySetInnerHTML={{__html:product.note}}/></div>}{tab==='specs'&&<dl className="divide-y rounded-2xl border">{product.specs.map(item=><div key={item.key} className="grid grid-cols-[160px_1fr] p-5 text-sm"><dt className="font-bold text-slate-500">{item.key}</dt><dd>{item.value}</dd></div>)}</dl>}{tab==='reviews'&&<div><div className="rounded-2xl bg-indigo-50 p-8 text-center"><b className="text-5xl">{product.reviewSummary.average||0}</b><p className="mt-2 text-sm text-indigo-700">구매 고객 리뷰 {product.reviewSummary.count}개</p></div><form onSubmit={review} className="mt-6 grid gap-3 rounded-2xl border p-5"><b>구매 리뷰 작성</b><select name="rating" className="rounded-lg border p-3 text-sm"><option value="5">★★★★★ 5점</option><option value="4">★★★★ 4점</option><option value="3">★★★ 3점</option><option value="2">★★ 2점</option><option value="1">★ 1점</option></select><textarea required name="body" className="min-h-24 rounded-lg border p-3 text-sm" placeholder="배송 완료된 구매 상품의 리뷰를 남겨주세요."/><button className="justify-self-end rounded-lg bg-slate-950 px-5 py-2 text-sm font-bold text-white">리뷰 등록</button></form><div className="mt-6 divide-y">{product.reviews.map(review=><article key={review.id} className="py-6"><div className="flex justify-between"><b>{review.userName}</b><span className="text-amber-500">{'★'.repeat(review.rating)}</span></div><p className="mt-3 text-sm leading-7">{review.body}</p></article>)}</div></div>}{tab==='questions'&&<div><form onSubmit={ask} className="grid gap-3 rounded-2xl bg-slate-50 p-5"><b>상품 문의하기</b><input name="title" required placeholder="문의 제목" className="rounded-lg border p-3 text-sm"/><textarea name="body" required placeholder="상품에 대해 궁금한 내용을 입력하세요." className="min-h-24 rounded-lg border p-3 text-sm"/><button className="justify-self-end rounded-lg bg-slate-950 px-5 py-2 text-sm font-bold text-white">문의 등록</button></form><div className="mt-6 divide-y">{product.questions.map(q=><article key={q.id} className="py-5"><b className="text-sm">Q. {q.title}</b><p className="mt-2 text-sm text-slate-600">{q.body}</p>{q.answer&&<p className="mt-3 rounded-lg bg-indigo-50 p-4 text-sm text-indigo-800"><b>A.</b> {q.answer}</p>}</article>)}</div></div>}</div></section>
    <section className="border-t py-16"><h2 className="text-2xl font-black">함께 보면 좋은 상품</h2><div className="mt-7 grid grid-cols-2 gap-4 md:grid-cols-4">{product.related.map(item=><ProductCard key={item.id} product={item} onAdd={p=>add(p)}/>)}</div></section>
  </main>;
}
