const { eq, and, desc, sql } = require('drizzle-orm');
const { database } = require('../../shared/db'); const { orders, orderItems } = require('../../shared/schema'); const { server, listen } = require('../../shared/http'); const { publish, subscribe } = require('../../shared/bus');
const { requireAuth, requireRole } = require('../../shared/auth'); const db = database('orders'); const app = server('order');
async function init() { await db.wait(); await db.query(`CREATE TABLE IF NOT EXISTS orders (id UUID PRIMARY KEY,user_id UUID NOT NULL,order_number TEXT UNIQUE NOT NULL,status TEXT NOT NULL,total_amount INTEGER NOT NULL,recipient TEXT NOT NULL,phone TEXT NOT NULL,address TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now())`); await db.query(`CREATE TABLE IF NOT EXISTS order_items (id UUID PRIMARY KEY,order_id UUID REFERENCES orders(id),product_id UUID NOT NULL,name TEXT NOT NULL,brand TEXT NOT NULL,image TEXT,unit_price INTEGER NOT NULL,quantity INTEGER NOT NULL)`); await subscribe('order', ['payment.approved', 'inventory.reserved', 'inventory.failed'], onEvent); }
async function onEvent(event) { const { orderId } = event.payload; if (event.type === 'payment.approved') await publish('inventory.reserve', { orderId, items: event.payload.items }); if (event.type === 'inventory.reserved') { const updated = await db.orm.update(orders).set({ status: 'confirmed' }).where(and(eq(orders.id, orderId), eq(orders.status, 'pending'))).returning({ userId: orders.userId, totalAmount: orders.totalAmount }); const order = updated[0]; if (order) await publish('order.confirmed', { orderId, userId: order.userId, totalAmount: order.totalAmount }); } if (event.type === 'inventory.failed') { const cancelled = await db.orm.update(orders).set({ status: 'cancelled' }).where(eq(orders.id, orderId)).returning({ userId: orders.userId }); if (cancelled[0]) await publish('order.cancelled', { orderId, userId: cancelled[0].userId, reason: 'OUT_OF_STOCK' }); } }
app.post('/orders', async (req, res) => { const { userId, items, shipping } = req.body; if (!userId || !Array.isArray(items) || !items.length || !shipping?.recipient || !shipping?.phone || !shipping?.address) return res.status(400).json({ code: 'INVALID_ORDER' }); const total = items.reduce((sum, item) => sum + item.price * item.quantity, 0); const id = crypto.randomUUID(); const orderNumber = `CM-${Date.now().toString().slice(-8)}`; await db.orm.insert(orders).values({ id, userId, orderNumber, status: 'pending', totalAmount: total, recipient: shipping.recipient, phone: shipping.phone, address: shipping.address }); await db.orm.insert(orderItems).values(items.map(item => ({ id: crypto.randomUUID(), orderId: id, productId: item.productId, name: item.name, brand: item.brand, image: item.image, unitPrice: item.price, quantity: item.quantity }))); await publish('order.created', { orderId: id, orderNumber, userId, items, totalAmount: total }); res.status(201).json({ id, orderNumber, status: 'pending', totalAmount: total }); });
app.get('/orders', async (req, res, next) => { if (!req.query.userId) return requireAuth(req, res, () => requireRole('admin')(req, res, next)); next(); }, async (req, res) => { const filter = req.query.userId ? eq(orders.userId, req.query.userId) : undefined; const rows = await db.orm.select({ id: orders.id, order_number: orders.orderNumber, user_id: orders.userId, status: orders.status, total_amount: orders.totalAmount, recipient: orders.recipient, created_at: orders.createdAt, item_count: sql`count(${orderItems.id})::int`, image: sql`min(${orderItems.image})` }).from(orders).leftJoin(orderItems, eq(orderItems.orderId, orders.id)).where(filter).groupBy(orders.id).orderBy(desc(orders.createdAt)).limit(100); res.json({ items: rows }); });
app.patch('/orders/:id/status', requireAuth, requireRole('admin'), async (req, res) => { const allowed = ['pending', 'confirmed', 'cancelled', 'preparing', 'shipped', 'delivered']; if (!allowed.includes(req.body.status)) return res.status(400).json({ code: 'INVALID_STATUS' }); const rows = await db.orm.update(orders).set({ status: req.body.status }).where(eq(orders.id, req.params.id)).returning(); rows[0] ? res.json({ id: rows[0].id, status: rows[0].status }) : res.status(404).json({ code: 'NOT_FOUND' }); });
app.get('/orders/:id', async (req, res) => { const rows = await db.orm.select().from(orders).where(eq(orders.id, req.params.id)).limit(1); if (!rows[0]) return res.status(404).json({ code: 'NOT_FOUND' }); const items = await db.orm.select().from(orderItems).where(eq(orderItems.orderId, req.params.id)); const order = rows[0]; res.json({ id: order.id, user_id: order.userId, order_number: order.orderNumber, status: order.status, total_amount: order.totalAmount, recipient: order.recipient, phone: order.phone, address: order.address, created_at: order.createdAt, items: items.map(item => ({ id: item.id, order_id: item.orderId, product_id: item.productId, name: item.name, brand: item.brand, image: item.image, unit_price: item.unitPrice, quantity: item.quantity })) }); });
init().then(() => listen(app, 'order')).catch(error => { console.error(error); process.exitCode = 1; });
